export interface AIModel {
  id: string;
  name: string;
  nameZh: string;
  developer: string;
  developerZh: string;
  releaseDate: string;
  category: "conversation" | "image-generation" | "video-generation" | "code" | "multimodal" | "open-source";
  description: string;
  descriptionZh: string;
  descriptionLong: string;
  descriptionLongZh: string;
  parameters: string;
  contextWindow: string;
  modalities: string[];
  languages: string[];
  openSource: boolean;
  license?: string;
  pricing: string;
  pricingZh: string;
  pricingTiers: { tier: string; tierZh: string; price: string; features: string[]; featuresZh: string[] }[];
  strengths: string[];
  strengthsZh: string[];
  weaknesses: string[];
  weaknessesZh: string[];
  bestFor: string[];
  bestForZh: string[];
  benchmarks?: { name: string; score: string; competitor?: string; competitorScore?: string }[];
  url: string;
  apiUrl?: string;
  githubUrl?: string;
  icon: string;
}

export const modelCategories = [
  "conversation",
  "image-generation",
  "video-generation",
  "code",
  "multimodal",
  "open-source",
] as const;

export type ModelCategory = (typeof modelCategories)[number];

export const modelCategoryLabels: Record<ModelCategory, { en: string; zh: string }> = {
  conversation: { en: "Conversation", zh: "对话" },
  "image-generation": { en: "Image Gen", zh: "图像生成" },
  "video-generation": { en: "Video Gen", zh: "视频生成" },
  code: { en: "Code", zh: "编程" },
  multimodal: { en: "Multimodal", zh: "多模态" },
  "open-source": { en: "Open Source", zh: "开源" },
};

export const models: AIModel[] = [
  // ========================================
  // Conversation / General (7)
  // ========================================
  {
    id: "gpt-4o",
    name: "GPT-4o",
    nameZh: "GPT-4o",
    developer: "OpenAI",
    developerZh: "OpenAI",
    releaseDate: "2024-05",
    category: "conversation",
    description: "OpenAI's flagship multimodal model combining text, vision, and audio in one unified interface.",
    descriptionZh: "OpenAI 的旗舰多模态模型，将文本、视觉和音频统一在一个界面中。",
    descriptionLong: "GPT-4o ('omni') is OpenAI's flagship multimodal model that natively integrates text, image, and audio processing. It accepts mixed inputs and generates text and image outputs with significantly lower latency than previous models. With an estimated 1.76 trillion parameters, it powers ChatGPT, the ChatGPT API, and Microsoft Copilot. GPT-4o excels at nuanced conversation, creative writing, code generation, data analysis, and vision understanding, making it one of the most versatile AI models available. Its voice mode with real-time emotional expression set a new standard for conversational AI.",
    descriptionLongZh: "GPT-4o（omni）是 OpenAI 的旗舰多模态模型，原生集成文本、图像和音频处理。它接受混合输入并生成文本和图像输出，延迟显著低于前代模型。估计参数量约 1.76 万亿，驱动着 ChatGPT、ChatGPT API 和 Microsoft Copilot。GPT-4o 在细腻对话、创意写作、代码生成、数据分析和视觉理解方面表现卓越，是目前最多功能的 AI 模型之一。其具备实时情感表达的语音模式为对话 AI 树立了新标准。",
    parameters: "Estimated ~1.76 trillion",
    contextWindow: "128K tokens",
    modalities: ["text", "image", "audio"],
    languages: ["English", "Chinese", "Spanish", "Arabic", "French", "German", "Japanese", "Korean", "50+ languages"],
    openSource: false,
    pricing: "Free / $20/mo Plus",
    pricingZh: "免费 / $20/月 Plus",
    pricingTiers: [
      {
        tier: "Free",
        tierZh: "免费版",
        price: "$0",
        features: ["GPT-4o mini access", "Limited GPT-5 messages", "Basic file uploads"],
        featuresZh: ["GPT-4o mini 访问", "有限 GPT-5 消息", "基础文件上传"],
      },
      {
        tier: "Plus",
        tierZh: "Plus 版",
        price: "$20/mo",
        features: ["Unlimited GPT-4o", "Advanced data analysis", "DALL-E 3", "Custom GPTs"],
        featuresZh: ["无限 GPT-4o 使用", "高级数据分析", "DALL-E 3", "自定义 GPTs"],
      },
      {
        tier: "API",
        tierZh: "API",
        price: "$2.50/1M input tokens",
        features: ["Pay-as-you-go", "128K context", "Vision & audio support"],
        featuresZh: ["按量计费", "128K 上下文", "视觉和音频支持"],
      },
    ],
    strengths: [
      "Multimodal in a single unified model (text + image + audio)",
      "Extremely fast response times with low latency",
      "Excellent creative writing and nuanced conversation",
      "Strong code generation and data analysis capabilities",
    ],
    strengthsZh: [
      "单一模型统一多模态（文本+图像+音频）",
      "响应速度极快，延迟低",
      "出色的创意写作和细腻对话能力",
      "强大的代码生成和数据分析能力",
    ],
    weaknesses: [
      "Estimated parameter count makes inference expensive at scale",
      "Occasional factual inaccuracies and hallucinations",
      "No native video generation capability",
    ],
    weaknessesZh: [
      "参数量大导致大规模推理成本较高",
      "偶尔出现事实错误和幻觉",
      "不具备原生视频生成能力",
    ],
    bestFor: [
      "Daily AI assistant for conversation and productivity",
      "Code generation and debugging across languages",
      "Creative content creation and brainstorming",
      "Data analysis with natural language queries",
    ],
    bestForZh: [
      "日常对话和效率提升的 AI 助手",
      "跨语言代码生成和调试",
      "创意内容创作和头脑风暴",
      "自然语言驱动的数据分析",
    ],
    benchmarks: [
      { name: "MMLU", score: "88.7%", competitor: "GPT-4", competitorScore: "86.4%" },
      { name: "HumanEval", score: "90.2%", competitor: "Claude 3.5 Sonnet", competitorScore: "92.0%" },
    ],
    url: "https://chat.openai.com",
    apiUrl: "https://platform.openai.com",
    icon: "\u{1F916}",
  },
  {
    id: "gpt-5",
    name: "GPT-5",
    nameZh: "GPT-5",
    developer: "OpenAI",
    developerZh: "OpenAI",
    releaseDate: "2025",
    category: "conversation",
    description: "OpenAI's latest flagship model with enhanced reasoning, larger context, and improved multimodality.",
    descriptionZh: "OpenAI 最新旗舰模型，推理能力更强、上下文更长、多模态更完善。",
    descriptionLong: "GPT-5 is OpenAI's latest flagship language model, building upon GPT-4o with major improvements in reasoning depth, context handling, and multimodal capabilities. It features a 256K token context window and enhanced capabilities across text, image, audio, and video understanding. GPT-5 demonstrates significantly improved performance on complex reasoning tasks, mathematical problem-solving, and long-form content generation. It powers the latest version of ChatGPT with higher message limits and more advanced features for Pro subscribers.",
    descriptionLongZh: "GPT-5 是 OpenAI 最新的旗舰语言模型，在 GPT-4o 基础上大幅提升了推理深度、上下文处理和多模态能力。它拥有 256K token 的上下文窗口，在文本、图像、音频和视频理解方面均有显著增强。GPT-5 在复杂推理任务、数学问题求解和长文生成方面表现大幅提升，驱动着最新版 ChatGPT，为 Pro 订阅者提供更高的消息上限和更高级的功能。",
    parameters: "Undisclosed (estimated >2 trillion)",
    contextWindow: "256K tokens",
    modalities: ["text", "image", "audio", "video"],
    languages: ["English", "Chinese", "Spanish", "Arabic", "French", "German", "50+ languages"],
    openSource: false,
    pricing: "$20/mo Plus / $200/mo Pro",
    pricingZh: "$20/月 Plus / $200/月 Pro",
    pricingTiers: [
      {
        tier: "Plus",
        tierZh: "Plus 版",
        price: "$20/mo",
        features: ["Unlimited GPT-5", "Advanced data analysis", "DALL-E 3", "Web browsing"],
        featuresZh: ["无限 GPT-5 使用", "高级数据分析", "DALL-E 3", "网页浏览"],
      },
      {
        tier: "Pro",
        tierZh: "Pro 版",
        price: "$200/mo",
        features: ["Unlimited GPT-5 Turbo", "Priority access", "Extended context 256K"],
        featuresZh: ["无限 GPT-5 Turbo", "优先访问", "扩展至 256K 上下文"],
      },
      {
        tier: "API",
        tierZh: "API",
        price: "TBD",
        features: ["Pay-as-you-go", "256K context", "Full multimodal"],
        featuresZh: ["按量计费", "256K 上下文", "全多模态"],
      },
    ],
    strengths: [
      "Improved reasoning and problem-solving over GPT-4o",
      "Larger 256K token context window",
      "Enhanced multimodal with video understanding",
      "Higher accuracy on complex tasks",
    ],
    strengthsZh: [
      "推理和问题解决能力超越 GPT-4o",
      "更大的 256K token 上下文窗口",
      "增强的多模态能力，支持视频理解",
      "复杂任务准确率更高",
    ],
    weaknesses: [
      "Premium pricing for Pro tier is expensive",
      "Limited availability through API",
      "Overkill for simple everyday tasks",
    ],
    weaknessesZh: [
      "Pro 版本价格较高",
      "API 可用性有限",
      "对简单日常任务来说过于强大",
    ],
    bestFor: [
      "Complex reasoning and advanced problem-solving",
      "Long-form content generation and analysis",
      "Professional research and deep analysis",
      "Enterprise-grade AI applications",
    ],
    bestForZh: [
      "复杂推理和高级问题解决",
      "长文内容生成和分析",
      "专业研究和深度分析",
      "企业级 AI 应用",
    ],
    url: "https://chat.openai.com",
    apiUrl: "https://platform.openai.com",
    icon: "\u{1F52E}",
  },
  {
    id: "claude-3-5-sonnet",
    name: "Claude 3.5 Sonnet",
    nameZh: "Claude 3.5 Sonnet",
    developer: "Anthropic",
    developerZh: "Anthropic",
    releaseDate: "2024-06",
    category: "conversation",
    description: "Anthropic's balanced model offering strong reasoning, coding, and long-context capabilities.",
    descriptionZh: "Anthropic 的均衡型模型，具备强大的推理、编程和长上下文能力。",
    descriptionLong: "Claude 3.5 Sonnet is Anthropic's mid-tier model that balances performance, speed, and cost. It features a 200K token context window allowing it to process entire books and extensive documents. Built with Constitutional AI for safety, Claude 3.5 Sonnet excels at nuanced writing, detailed analysis, code generation, and following complex instructions. It consistently outperforms larger models on coding benchmarks and is favored by developers for its thoughtful, well-structured responses. The model is available through Claude.ai, the Anthropic API, and Amazon Bedrock.",
    descriptionLongZh: "Claude 3.5 Sonnet 是 Anthropic 的中端模型，在性能、速度和成本之间取得了良好平衡。它拥有 200K token 的上下文窗口，可以处理整本书籍和长篇文档。基于 Constitutional AI 构建，在细腻写作、详细分析、代码生成和遵循复杂指令方面表现出色。在编程基准测试上持续超越更大模型，因其深思熟虑且结构清晰的回复受到开发者青睐。",
    parameters: "Undisclosed",
    contextWindow: "200K tokens",
    modalities: ["text", "image"],
    languages: ["English", "Chinese", "Spanish", "Arabic", "French", "German", "Japanese", "50+ languages"],
    openSource: false,
    pricing: "Free / $20/mo Pro",
    pricingZh: "免费 / $20/月 Pro",
    pricingTiers: [
      {
        tier: "Free",
        tierZh: "免费版",
        price: "$0",
        features: ["Claude 3.5 Sonnet access", "Limited daily messages", "Basic uploads"],
        featuresZh: ["Claude 3.5 Sonnet 访问", "每日有限消息", "基础上传"],
      },
      {
        tier: "Pro",
        tierZh: "Pro 版",
        price: "$20/mo",
        features: ["Unlimited Sonnet", "Claude 4 Opus access", "Projects"],
        featuresZh: ["无限 Sonnet 使用", "Claude 4 Opus 访问", "项目功能"],
      },
      {
        tier: "API",
        tierZh: "API",
        price: "$3.00/1M input tokens",
        features: ["Pay-as-you-go", "200K context", "Vision support"],
        featuresZh: ["按量计费", "200K 上下文", "视觉支持"],
      },
    ],
    strengths: [
      "Excellent coding ability, leading many benchmarks",
      "200K token context for processing entire documents",
      "Superior writing quality and nuanced output",
      "Strong safety alignment without capability sacrifice",
    ],
    strengthsZh: [
      "优秀的编程能力，领先多项基准测试",
      "200K token 上下文可处理整篇文档",
      "卓越的写作质量和细腻输出",
      "强大的安全对齐，不牺牲能力",
    ],
    weaknesses: [
      "No native image generation",
      "Strict rate limits on free tier",
      "Slower than Haiku for simple tasks",
    ],
    weaknessesZh: [
      "不支持原生图像生成",
      "免费版速率限制较严格",
      "简单任务比 Haiku 慢",
    ],
    bestFor: [
      "Complex coding tasks and software development",
      "Long document analysis and research",
      "Content editing and creative writing",
      "Detailed analytical work requiring nuance",
    ],
    bestForZh: [
      "复杂编程任务和软件开发",
      "长文档分析和研究",
      "内容编辑和创意写作",
      "需要细致分析的工作",
    ],
    benchmarks: [
      { name: "MMLU", score: "88.7%", competitor: "GPT-4o", competitorScore: "88.7%" },
      { name: "HumanEval", score: "92.0%", competitor: "GPT-4o", competitorScore: "90.2%" },
    ],
    url: "https://claude.ai",
    apiUrl: "https://api.anthropic.com",
    icon: "\u{1F9E0}",
  },
  {
    id: "claude-4-opus",
    name: "Claude 4 Opus",
    nameZh: "Claude 4 Opus",
    developer: "Anthropic",
    developerZh: "Anthropic",
    releaseDate: "2025",
    category: "conversation",
    description: "Anthropic's most powerful model for complex reasoning, research, and specialized tasks.",
    descriptionZh: "Anthropic 最强大的模型，专为复杂推理、研究和专业任务打造。",
    descriptionLong: "Claude 4 Opus is Anthropic's most capable model, designed for complex reasoning, research, and specialized tasks requiring deep analytical thinking. It features a 200K token context window and enhanced multimodal capabilities. Claude 4 Opus represents a significant leap in reasoning depth, scientific knowledge, and nuanced understanding compared to previous generations. It is the preferred choice for professionals working on cutting-edge research, complex mathematical proofs, legal analysis, and any domain requiring the highest level of cognitive performance.",
    descriptionLongZh: "Claude 4 Opus 是 Anthropic 能力最强的模型，专为复杂推理、研究和需要深度分析思维的专业任务而设计。它拥有 200K token 上下文窗口和增强的多模态能力。与前代相比，Claude 4 Opus 在推理深度、科学知识和细腻理解方面实现了重大飞跃。它是从事前沿研究、复杂数学证明、法律分析和任何需要最高认知水平工作的专业人士的首选。",
    parameters: "Undisclosed",
    contextWindow: "200K tokens",
    modalities: ["text", "image", "audio"],
    languages: ["English", "Chinese", "Spanish", "Arabic", "French", "German", "50+ languages"],
    openSource: false,
    pricing: "$20/mo Pro / $30/user/mo Team",
    pricingZh: "$20/月 Pro / $30/用户/月 Team",
    pricingTiers: [
      {
        tier: "Pro",
        tierZh: "Pro 版",
        price: "$20/mo",
        features: ["Claude 4 Opus access", "Higher rate limits", "Projects"],
        featuresZh: ["Claude 4 Opus 访问", "更高速率限制", "项目功能"],
      },
      {
        tier: "Team",
        tierZh: "团队版",
        price: "$30/user/mo",
        features: ["All Pro features", "Shared workspaces", "Priority support"],
        featuresZh: ["所有 Pro 功能", "共享工作区", "优先支持"],
      },
      {
        tier: "API",
        tierZh: "API",
        price: "$15.00/1M input tokens",
        features: ["Pay-as-you-go", "200K context", "Multimodal input"],
        featuresZh: ["按量计费", "200K 上下文", "多模态输入"],
      },
    ],
    strengths: [
      "Deepest reasoning and analytical capabilities in Claude family",
      "Exceptional at scientific and technical domains",
      "Superior long-context understanding and recall",
      "Advanced multimodal understanding",
    ],
    strengthsZh: [
      "Claude 系列中最强的推理和分析能力",
      "在科学和技术领域表现卓越",
      "出色的长上下文理解和记忆能力",
      "高级多模态理解能力",
    ],
    weaknesses: [
      "Higher cost per token than Sonnet",
      "Slower response times for deep reasoning",
      "Over-provisioned for simple daily tasks",
    ],
    weaknessesZh: [
      "每 token 成本高于 Sonnet",
      "深度推理时响应较慢",
      "对简单日常任务来说能力过剩",
    ],
    bestFor: [
      "Advanced research and scientific analysis",
      "Complex legal document review",
      "Mathematical reasoning and proofs",
      "High-stakes professional decision support",
    ],
    bestForZh: [
      "高级研究和科学分析",
      "复杂法律文档审阅",
      "数学推理和证明",
      "高专业性决策支持",
    ],
    url: "https://claude.ai",
    apiUrl: "https://api.anthropic.com",
    icon: "\u{1F3AF}",
  },
  {
    id: "gemini-2-5-pro",
    name: "Gemini 2.5 Pro",
    nameZh: "Gemini 2.5 Pro",
    developer: "Google DeepMind",
    developerZh: "Google DeepMind",
    releaseDate: "2025-03",
    category: "multimodal",
    description: "Google's most advanced model with the largest context window and native multimodal processing.",
    descriptionZh: "Google 最先进的模型，拥有最大上下文窗口和原生多模态处理能力。",
    descriptionLong: "Gemini 2.5 Pro is Google DeepMind's most advanced AI model, featuring an unprecedented 1 million token context window — the largest of any commercial AI model. It natively processes text, images, audio, video, and code simultaneously without separate tools. Deeply integrated with Google Search, it has real-time access to current information. Gemini 2.5 Pro demonstrates breakthrough performance on reasoning benchmarks and excels at processing extremely long documents, codebases, and video content. Available through Google AI Studio and Vertex AI.",
    descriptionLongZh: "Gemini 2.5 Pro 是 Google DeepMind 最先进的 AI 模型，拥有前所未有的 100 万 token 上下文窗口——是所有商业 AI 模型中最大的。它原生同时处理文本、图像、音频、视频和代码，无需分离工具。深度集成 Google 搜索，可实时访问最新信息。Gemini 2.5 Pro 在推理基准测试中表现突破，擅长处理超长文档、代码库和视频内容。",
    parameters: "Undisclosed",
    contextWindow: "1M tokens (up to 2M in preview)",
    modalities: ["text", "image", "audio", "video", "code"],
    languages: ["English", "Chinese", "Spanish", "Arabic", "French", "German", "Japanese", "50+ languages"],
    openSource: false,
    pricing: "Free tier / $19.99/mo Advanced",
    pricingZh: "免费版 / $19.99/月 Advanced",
    pricingTiers: [
      {
        tier: "Free",
        tierZh: "免费版",
        price: "$0",
        features: ["Gemini 2.5 Pro access", "Google Search", "File uploads"],
        featuresZh: ["Gemini 2.5 Pro 访问", "Google 搜索", "文件上传"],
      },
      {
        tier: "Advanced",
        tierZh: "Advanced 版",
        price: "$19.99/mo",
        features: ["1M token context", "Priority access", "1TB Drive storage"],
        featuresZh: ["100 万 token 上下文", "优先访问", "1TB Drive 存储"],
      },
      {
        tier: "API",
        tierZh: "API",
        price: "$1.25/1M input tokens",
        features: ["Pay-as-you-go", "Up to 2M context", "Video understanding"],
        featuresZh: ["按量计费", "最高 200 万上下文", "视频理解"],
      },
    ],
    strengths: [
      "Largest context window of any commercial model at 1M tokens",
      "Native multimodal processing of text, image, audio, video, and code",
      "Real-time Google Search integration for current information",
      "Strong reasoning benchmarks and STEM performance",
    ],
    strengthsZh: [
      "所有商业模型中最大的上下文窗口（100 万 token）",
      "原生多模态处理文本、图像、音频、视频和代码",
      "实时 Google 搜索集成获取最新信息",
      "推理基准测试和 STEM 表现强大",
    ],
    weaknesses: [
      "Creative writing less nuanced than Claude",
      "Privacy concerns with Google data handling",
      "Some features limited to Google ecosystem",
    ],
    weaknessesZh: [
      "创意写作不如 Claude 细腻",
      "Google 数据处理引发隐私担忧",
      "部分功能限于 Google 生态",
    ],
    bestFor: [
      "Processing extremely long documents and codebases",
      "Multimodal analysis combining text, video, and audio",
      "Research with real-time web search integration",
      "STEM problem-solving and mathematical reasoning",
    ],
    bestForZh: [
      "处理超长文档和代码库",
      "结合文本、视频和音频的多模态分析",
      "集成实时网络搜索的研究",
      "STEM 问题求解和数学推理",
    ],
    benchmarks: [
      { name: "MMMU", score: "87.4%", competitor: "GPT-4o", competitorScore: "82.1%" },
      { name: "MathArena", score: "93.1%", competitor: "Claude 4 Opus", competitorScore: "91.5%" },
    ],
    url: "https://gemini.google.com",
    apiUrl: "https://ai.google.dev",
    icon: "\u{1F31F}",
  },
  {
    id: "deepseek-r1",
    name: "DeepSeek-R1",
    nameZh: "DeepSeek-R1",
    developer: "DeepSeek",
    developerZh: "深度求索",
    releaseDate: "2025-01",
    category: "conversation",
    description: "Open-weight reasoning model with Chain-of-Thought, rivaling top proprietary models.",
    descriptionZh: "开源权重推理模型，具备思维链能力，媲美顶级闭源模型。",
    descriptionLong: "DeepSeek-R1 is a groundbreaking open-weight reasoning model developed by DeepSeek (深度求索). It features 671 billion total parameters with 37 billion activated per token using Mixture-of-Experts architecture. R1 introduces explicit Chain-of-Thought reasoning, demonstrating performance comparable to OpenAI's o1 on mathematical reasoning, coding, and scientific problem-solving. Its open-weight release under a permissive license sparked widespread adoption in the AI community. At a fraction of the cost of proprietary alternatives, DeepSeek-R1 democratized access to advanced reasoning AI.",
    descriptionLongZh: "DeepSeek-R1 是深度求索开发的一款突破性的开源权重推理模型。它采用混合专家架构，总参数量 6710 亿，每个 token 激活 370 亿参数。R1 引入了显式思维链推理，在数学推理、编程和科学问题求解方面表现出与 OpenAI o1 相当的性能。其宽松许可下的开源权重发布在 AI 社区引发了广泛采用。以专有模型零头的成本，DeepSeek-R1 使高级推理 AI 的获取更加民主化。",
    parameters: "671B total (37B active per token)",
    contextWindow: "128K tokens",
    modalities: ["text"],
    languages: ["English", "Chinese"],
    openSource: true,
    license: "MIT",
    pricing: "Free / API from $0.14/M tokens",
    pricingZh: "免费 / API 从 $0.14/百万 token",
    pricingTiers: [
      {
        tier: "Free Chat",
        tierZh: "免费聊天",
        price: "$0",
        features: ["Unlimited DeepSeek chat", "DeepSeek-R1 model", "File uploads"],
        featuresZh: ["无限 DeepSeek 聊天", "DeepSeek-R1 模型", "文件上传"],
      },
      {
        tier: "API",
        tierZh: "API",
        price: "From $0.14/M tokens",
        features: ["R1 and V3 API", "Rate limits", "Fine-tuning available"],
        featuresZh: ["R1 和 V3 API", "速率限制", "支持微调"],
      },
      {
        tier: "Self-Hosted",
        tierZh: "自部署",
        price: "Free (open-weight)",
        features: ["Full model weights", "Custom deployment", "Unlimited usage"],
        featuresZh: ["完整模型权重", "自定义部署", "无限使用"],
      },
    ],
    strengths: [
      "Open-weight with permissive MIT license",
      "Chain-of-Thought reasoning rivaling top proprietary models",
      "Exceptional cost efficiency (fraction of competitors' API cost)",
      "Strong math and coding performance",
    ],
    strengthsZh: [
      "开源权重，MIT 许可",
      "思维链推理媲美顶级专有模型",
      "极高的成本效益（竞争对手 API 成本的零头）",
      "优秀的数学和编程性能",
    ],
    weaknesses: [
      "Text-only model, no vision or multimodal",
      "Less refined conversational ability",
      "Server availability can be inconsistent",
      "Documentation primarily in Chinese",
    ],
    weaknessesZh: [
      "仅支持文本，无视觉或多模态能力",
      "对话能力不如闭源模型细腻",
      "服务器可用性不稳定",
      "文档主要以中文为主",
    ],
    bestFor: [
      "Self-hosting advanced reasoning AI on own infrastructure",
      "Mathematical problem-solving and proofs",
      "Competitive coding and algorithm challenges",
      "Cost-sensitive AI integration at scale",
    ],
    bestForZh: [
      "在自有基础设施上自部署高级推理 AI",
      "数学问题求解和证明",
      "竞赛编程和算法挑战",
      "大规模成本敏感的 AI 集成",
    ],
    benchmarks: [
      { name: "AIME 2025", score: "79.8%", competitor: "o1 (OpenAI)", competitorScore: "79.2%" },
      { name: "MATH-500", score: "97.3%", competitor: "o1", competitorScore: "96.4%" },
    ],
    url: "https://chat.deepseek.com",
    apiUrl: "https://platform.deepseek.com",
    githubUrl: "https://github.com/deepseek-ai/DeepSeek-R1",
    icon: "\u{1F50D}",
  },
  {
    id: "llama-4",
    name: "Llama 4",
    nameZh: "Llama 4",
    developer: "Meta AI",
    developerZh: "Meta AI",
    releaseDate: "2025",
    category: "open-source",
    description: "Meta's next-generation open-weight LLM with MoE architecture and strong multilingual support.",
    descriptionZh: "Meta 的下一代开源权重大语言模型，采用 MoE 架构，多语言支持强大。",
    descriptionLong: "Llama 4 is Meta's latest open-weight large language model, built on a Mixture-of-Experts (MoE) architecture for improved efficiency. With a 128K token context window, Llama 4 offers strong performance across reasoning, coding, and multilingual tasks. As an open-weight model under a custom commercial license, it enables developers and enterprises to deploy, fine-tune, and customize the model for specific use cases. Early benchmarks show Llama 4 competitive with GPT-4o and Claude 3.5 Sonnet on several key metrics while being significantly more efficient to run.",
    descriptionLongZh: "Llama 4 是 Meta 最新的开源权重大语言模型，采用混合专家（MoE）架构以提高效率。拥有 128K token 的上下文窗口，在推理、编程和多语言任务上表现强劲。作为采用自定义商业许可的开源权重模型，它使开发者和企业能够部署、微调并根据特定用例进行定制。早期基准测试显示 Llama 4 在多项关键指标上与 GPT-4o 和 Claude 3.5 Sonnet 竞争，同时运行效率显著更高。",
    parameters: "Undisclosed (MoE, estimated ~300B total)",
    contextWindow: "128K tokens",
    modalities: ["text", "image"],
    languages: ["English", "Chinese", "Spanish", "Arabic", "French", "German", "Hindi", "Portuguese", "100+ languages"],
    openSource: true,
    license: "Llama 4 Community License",
    pricing: "Free (open-weight) / API from $0.20/M tokens",
    pricingZh: "免费（开源权重）/ API 从 $0.20/百万 token",
    pricingTiers: [
      {
        tier: "Self-Hosted",
        tierZh: "自部署",
        price: "$0",
        features: ["Full model weights", "Unlimited usage", "Fine-tuning allowed"],
        featuresZh: ["完整模型权重", "无限使用", "支持微调"],
      },
      {
        tier: "API (Together/Groq)",
        tierZh: "API（Together/Groq）",
        price: "From $0.20/M tokens",
        features: ["Hosted inference", "Rate limits", "No GPU needed"],
        featuresZh: ["托管推理", "速率限制", "无需 GPU"],
      },
    ],
    strengths: [
      "Open-weight for self-hosting and customization",
      "MoE architecture for efficient inference",
      "Strong multilingual support across 100+ languages",
      "Competitive performance with leading proprietary models",
    ],
    strengthsZh: [
      "开源权重，可自部署和定制",
      "MoE 架构实现高效推理",
      "支持 100+ 语言的强大多语言能力",
      "性能与领先专有模型竞争",
    ],
    weaknesses: [
      "Commercial license has usage restrictions for large apps",
      "Smaller ecosystem compared to Llama 3",
      "Some benchmarks below top proprietary models",
    ],
    weaknessesZh: [
      "商业许可对大型应用有使用限制",
      "生态系统不如 Llama 3 成熟",
      "部分基准测试低于顶级专有模型",
    ],
    bestFor: [
      "Self-hosted enterprise AI deployments",
      "Fine-tuned domain-specific applications",
      "Multilingual content generation and translation",
      "Research and experimentation with LLMs",
    ],
    bestForZh: [
      "自部署的企业级 AI",
      "针对特定领域的微调应用",
      "多语言内容生成和翻译",
      "LLM 研究和实验",
    ],
    url: "https://llama.meta.com",
    githubUrl: "https://github.com/meta-llama/llama-models",
    icon: "\u{1F989}",
  },

  // ========================================
  // Image Generation (5)
  // ========================================
  {
    id: "midjourney-v7",
    name: "Midjourney V7",
    nameZh: "Midjourney V7",
    developer: "Midjourney Inc.",
    developerZh: "Midjourney Inc.",
    releaseDate: "2025",
    category: "image-generation",
    description: "The highest-quality AI image generator with cinematic output and advanced style control.",
    descriptionZh: "最高质量的 AI 图像生成器，电影级输出和高级风格控制。",
    descriptionLong: "Midjourney V7 is the latest version of the leading AI image generation platform, renowned for producing the highest-quality artistic images. Operating through Discord and a web interface, V7 introduces improved photorealism, better prompt adherence, and advanced parameter controls for fine-grained style, composition, and lighting adjustments. Midjourney has become the go-to tool for professional artists, game designers, and creative agencies worldwide. V7 also features enhanced character consistency, expanded aspect ratios, and a new personalization engine that learns from user preferences.",
    descriptionLongZh: "Midjourney V7 是领先 AI 图像生成平台的最新版本，以制作最高质量的艺术图像而闻名。通过 Discord 和网页界面操作，V7 引入了改进的照片真实感、更好的指令遵循能力以及用于精细风格、构图和光线调整的高级参数控制。Midjourney 已成为全球专业艺术家、游戏设计师和创意机构的首选工具。V7 还增强了角色一致性、扩展了宽高比，并新增了从用户偏好中学习的个性化引擎。",
    parameters: "N/A (diffusion model)",
    contextWindow: "N/A",
    modalities: ["text", "image"],
    languages: ["English"],
    openSource: false,
    pricing: "From $10/mo",
    pricingZh: "从 $10/月",
    pricingTiers: [
      {
        tier: "Basic",
        tierZh: "基础版",
        price: "$10/mo",
        features: ["3.3 hrs/month GPU", "Commercial license", "Web gallery"],
        featuresZh: ["3.3 小时/月 GPU", "商业许可", "在线画廊"],
      },
      {
        tier: "Standard",
        tierZh: "标准版",
        price: "$30/mo",
        features: ["15 hrs/month GPU", "Stealth mode", "Relax priority"],
        featuresZh: ["15 小时/月 GPU", "隐身模式", "放松优先级"],
      },
      {
        tier: "Pro",
        tierZh: "Pro 版",
        price: "$60/mo",
        features: ["30 hrs/month GPU", "Priority queue", "Parallel jobs"],
        featuresZh: ["30 小时/月 GPU", "优先队列", "并行任务"],
      },
    ],
    strengths: [
      "Highest artistic and aesthetic quality available",
      "Advanced parameter system for fine-grained control",
      "Excellent character and style consistency in V7",
      "Strong community with millions of shared creations",
    ],
    strengthsZh: [
      "目前最高的艺术和美学质量",
      "高级参数系统实现精细控制",
      "V7 出色的角色和风格一致性",
      "拥有数百万共享作品的强大社区",
    ],
    weaknesses: [
      "Requires Discord for primary interface",
      "Steep learning curve for advanced parameters",
      "No free tier available",
      "Less flexible than open-source alternatives",
    ],
    weaknessesZh: [
      "主要界面依赖 Discord",
      "高级参数学习曲线陡峭",
      "没有免费版本",
      "灵活性不如开源替代方案",
    ],
    bestFor: [
      "Concept art and visual development",
      "Brand and marketing visuals",
      "Book and publication illustrations",
      "Creative prototyping and mood boarding",
    ],
    bestForZh: [
      "概念艺术和视觉开发",
      "品牌和营销视觉素材",
      "书籍和出版物插图",
      "创意原型和情绪板制作",
    ],
    url: "https://www.midjourney.com",
    icon: "\u{1F3A8}",
  },
  {
    id: "dalle-3",
    name: "DALL-E 3",
    nameZh: "DALL-E 3",
    developer: "OpenAI",
    developerZh: "OpenAI",
    releaseDate: "2023-10",
    category: "image-generation",
    description: "OpenAI's image generator with superior prompt adherence, integrated into ChatGPT.",
    descriptionZh: "OpenAI 的图像生成器，指令遵循能力卓越，集成在 ChatGPT 中。",
    descriptionLong: "DALL-E 3 is OpenAI's latest image generation model, setting new standards for prompt adherence and text rendering accuracy. Deeply integrated into ChatGPT, users can generate, refine, and iterate on images through natural conversation. DALL-E 3 excels at following complex, detailed prompts with high precision, generating high-resolution images that accurately reflect the described scenes, objects, and styles. Its tight ChatGPT integration enables seamless workflows where users can describe an idea, refine it through dialogue, and export the final image without leaving the chat.",
    descriptionLongZh: "DALL-E 3 是 OpenAI 最新的图像生成模型，在指令遵循和文字渲染准确性方面树立了新标准。它深度集成到 ChatGPT 中，用户可以通过自然对话生成、优化和迭代图像。DALL-E 3 擅长以高精度遵循复杂详细的提示，生成准确反映所描述场景、物体和风格的高分辨率图像。与 ChatGPT 的紧密集成使用户可以在不离开聊天的情况下描述想法、通过对话优化并导出最终图像。",
    parameters: "Undisclosed",
    contextWindow: "N/A",
    modalities: ["text", "image"],
    languages: ["English", "Chinese", "Spanish", "Arabic", "50+ languages"],
    openSource: false,
    pricing: "Included with ChatGPT Plus ($20/mo)",
    pricingZh: "包含在 ChatGPT Plus 中（$20/月）",
    pricingTiers: [
      {
        tier: "ChatGPT Free",
        tierZh: "ChatGPT 免费版",
        price: "$0",
        features: ["Limited DALL-E 3 generations", "Standard resolution"],
        featuresZh: ["有限 DALL-E 3 生成", "标准分辨率"],
      },
      {
        tier: "ChatGPT Plus",
        tierZh: "ChatGPT Plus",
        price: "$20/mo",
        features: ["Unlimited DALL-E 3", "HD resolution", "Iterative refinement"],
        featuresZh: ["无限 DALL-E 3 生成", "高清分辨率", "迭代优化"],
      },
    ],
    strengths: [
      "Best-in-class prompt adherence and text rendering",
      "Seamless ChatGPT integration for natural refinement",
      "Fast generation speed and quick iteration",
      "Accessible through the most popular AI interface",
    ],
    strengthsZh: [
      "一流的指令遵循能力和文字渲染",
      "无缝 ChatGPT 集成，自然迭代优化",
      "生成速度快，迭代迅速",
      "通过最流行的 AI 界面访问",
    ],
    weaknesses: [
      "Less artistic quality compared to Midjourney",
      "Requires ChatGPT subscription for full access",
      "Less control over fine details and composition",
    ],
    weaknessesZh: [
      "艺术质量不如 Midjourney",
      "完整使用需要 ChatGPT 订阅",
      "对细节和构图的控制较少",
    ],
    bestFor: [
      "Quick visual ideation and prototyping",
      "Social media graphics and blog illustrations",
      "Marketing materials and ad creatives",
      "Integrated workflow within ChatGPT",
    ],
    bestForZh: [
      "快速视觉构思和原型设计",
      "社交媒体图形和博客插图",
      "营销材料和广告创意",
      "ChatGPT 集成工作流",
    ],
    url: "https://openai.com/dall-e-3",
    icon: "\u{1F5BC}️",
  },
  {
    id: "stable-diffusion-3-5",
    name: "Stable Diffusion 3.5",
    nameZh: "Stable Diffusion 3.5",
    developer: "Stability AI",
    developerZh: "Stability AI",
    releaseDate: "2024-10",
    category: "open-source",
    description: "Open-source image generation model with local execution, full privacy, and community ecosystem.",
    descriptionZh: "开源图像生成模型，支持本地运行、完全隐私和社区生态系统。",
    descriptionLong: "Stable Diffusion 3.5 is Stability AI's latest open-source image generation model, available in 8B parameter configurations. It runs locally on consumer GPUs, offering complete privacy, unlimited free generation, and deep customization through fine-tuning and community extensions. The open ecosystem includes thousands of community-trained LoRAs, checkpoints, and ControlNet models. ComfyUI and Automatic1111 provide powerful node-based and traditional interfaces. SD 3.5 represents the pinnacle of open-source image generation with improved prompt adherence, better anatomy, and higher aesthetic quality than previous versions.",
    descriptionLongZh: "Stable Diffusion 3.5 是 Stability AI 最新开源的图像生成模型，提供 8B 参数配置。它在消费级 GPU 上本地运行，提供完全的隐私保护、无限的免费生成以及通过微调和社区扩展实现的深度定制。开源生态系统包含数千个社区训练的 LoRA、检查点和 ControlNet 模型。ComfyUI 和 Automatic1111 提供强大的节点式界面和传统界面。SD 3.5 代表了开源图像生成的巅峰，相比前代在指令遵循、人体结构和美学质量方面均有改进。",
    parameters: "8B",
    contextWindow: "N/A",
    modalities: ["text", "image"],
    languages: ["English"],
    openSource: true,
    license: "Stability AI Non-Commercial / Commercial",
    pricing: "Free (open-source)",
    pricingZh: "免费（开源）",
    pricingTiers: [
      {
        tier: "Self-Hosted",
        tierZh: "自部署",
        price: "$0",
        features: ["Unlimited generation", "Full privacy", "All community models"],
        featuresZh: ["无限生成", "完全隐私", "所有社区模型"],
      },
      {
        tier: "API",
        tierZh: "API",
        price: "Pay-as-you-go",
        features: ["Cloud hosted", "API access", "No GPU needed"],
        featuresZh: ["云端托管", "API 访问", "无需 GPU"],
      },
    ],
    strengths: [
      "Free with unlimited local generation",
      "Full privacy with local execution",
      "Extensive community ecosystem of models and tools",
      "Deep customization through fine-tuning and LoRAs",
    ],
    strengthsZh: [
      "免费且本地无限生成",
      "本地运行保证完全隐私",
      "庞大的社区模型和工具生态系统",
      "通过微调和 LoRA 深度定制",
    ],
    weaknesses: [
      "Requires powerful GPU for good performance",
      "Steep learning curve for advanced workflows",
      "Complex setup and configuration",
      "Quality varies across community models",
    ],
    weaknessesZh: [
      "需要强力的 GPU 才能获得良好性能",
      "高级工作流学习曲线陡峭",
      "安装配置复杂",
      "社区模型质量参差不齐",
    ],
    bestFor: [
      "Unlimited private image generation",
      "Custom model fine-tuning and training",
      "Advanced AI art techniques (ControlNet, IP-Adapter)",
      "Building AI image applications and pipelines",
    ],
    bestForZh: [
      "无限私有的图像生成",
      "自定义模型微调和训练",
      "高级 AI 艺术技巧（ControlNet、IP-Adapter）",
      "构建 AI 图像应用和流程",
    ],
    url: "https://stability.ai",
    githubUrl: "https://github.com/Stability-AI/generative-models",
    icon: "\u{26A1}",
  },
  {
    id: "flux-1-pro",
    name: "FLUX.1 Pro",
    nameZh: "FLUX.1 Pro",
    developer: "Black Forest Labs",
    developerZh: "Black Forest Labs",
    releaseDate: "2024-08",
    category: "image-generation",
    description: "Open-weight image generation model with 12B parameters, rivaling Midjourney quality.",
    descriptionZh: "开源权重图像生成模型，12B 参数，质量媲美 Midjourney。",
    descriptionLong: "FLUX.1 Pro is a state-of-the-art open-weight image generation model developed by Black Forest Labs, founded by former Stability AI researchers. With 12 billion parameters, it produces images competitive with Midjourney in aesthetic quality while offering greater flexibility through open weights. FLUX.1 Pro excels at photorealism, accurate anatomy, and text rendering in images. Available under both open-weight (non-commercial) and API licenses, it has quickly become a favorite in the AI art community for its exceptional quality and prompt adherence.",
    descriptionLongZh: "FLUX.1 Pro 是由 Black Forest Labs（由前 Stability AI 研究员创立）开发的最先进开源权重图像生成模型。凭借 120 亿参数，它在美学质量上可与 Midjourney 竞争，同时通过开放权重提供更大的灵活性。FLUX.1 Pro 在照片真实感、准确的人体结构和图像文字渲染方面表现出色。它提供开源权重（非商业）和 API 许可两种方式，因其卓越的质量和指令遵循能力迅速成为 AI 艺术社区的新宠。",
    parameters: "12B",
    contextWindow: "N/A",
    modalities: ["text", "image"],
    languages: ["English"],
    openSource: true,
    license: "FLUX.1-dev Non-Commercial / API Commercial",
    pricing: "Free (open-weight for non-commercial) / API",
    pricingZh: "免费（非商业开源权重）/ API",
    pricingTiers: [
      {
        tier: "Open Weights",
        tierZh: "开源权重",
        price: "$0 (non-commercial)",
        features: ["12B parameter model", "Local execution", "Non-commercial use"],
        featuresZh: ["12B 参数模型", "本地运行", "非商业使用"],
      },
      {
        tier: "API",
        tierZh: "API",
        price: "Pay-as-you-go",
        features: ["Commercial license", "Cloud hosted", "Priority queue"],
        featuresZh: ["商业许可", "云端托管", "优先队列"],
      },
    ],
    strengths: [
      "12B parameters for exceptional image quality",
      "Competitive with Midjourney in photorealism",
      "Open-weight flexibility for customization",
      "Excellent anatomy and text rendering",
    ],
    strengthsZh: [
      "12B 参数带来卓越图像质量",
      "照片真实感可与 Midjourney 竞争",
      "开源权重灵活性便于定制",
      "出色的人体结构和文字渲染",
    ],
    weaknesses: [
      "Non-commercial license for open weights",
      "Requires substantial GPU memory (24GB+)",
      "Smaller community ecosystem than SD",
    ],
    weaknessesZh: [
      "开源权重仅限非商业使用",
      "需要大量 GPU 内存（24GB+）",
      "社区生态系统不如 SD 成熟",
    ],
    bestFor: [
      "High-quality photorealistic image generation",
      "Commercial image generation via API",
      "Research and experimentation with diffusion models",
      "Text rendering in generated images",
    ],
    bestForZh: [
      "高质量照片级图像生成",
      "通过 API 进行商业图像生成",
      "扩散模型研究和实验",
      "生成图像中的文字渲染",
    ],
    url: "https://blackforestlabs.ai",
    githubUrl: "https://github.com/black-forest-labs/flux",
    icon: "\u{1F4A5}",
  },
  {
    id: "adobe-firefly-3",
    name: "Adobe Firefly 3",
    nameZh: "Adobe Firefly 3",
    developer: "Adobe Inc.",
    developerZh: "Adobe Inc.",
    releaseDate: "2025",
    category: "image-generation",
    description: "Adobe's generative AI for professional design, integrated with Creative Cloud tools.",
    descriptionZh: "Adobe 的专业设计生成式 AI，深度集成 Creative Cloud 工具。",
    descriptionLong: "Adobe Firefly 3 is Adobe's latest generative AI model family, deeply integrated into Creative Cloud applications like Photoshop, Illustrator, and Express. Firefly 3 introduces significantly improved image quality, faster generation, and new capabilities including Generative Fill, Generative Expand, text-to-vector, and text-to-template. Trained on licensed content, Firefly is commercially safe for enterprise use. Its deep integration with Adobe's professional tools makes it the natural choice for designers already working in the Adobe ecosystem, offering AI capabilities directly within existing workflows.",
    descriptionLongZh: "Adobe Firefly 3 是 Adobe 最新的生成式 AI 模型系列，深度集成到 Photoshop、Illustrator 和 Express 等 Creative Cloud 应用中。Firefly 3 显著提升了图像质量、加快了生成速度，并引入了生成式填充、生成式扩展、文字转矢量图和文字转模板等新功能。基于授权内容训练，Firefly 对企业使用来说具有商业安全性。与 Adobe 专业工具的深度集成使其成为 Adobe 生态中设计师的自然选择。",
    parameters: "Undisclosed",
    contextWindow: "N/A",
    modalities: ["text", "image", "vector"],
    languages: ["English", "Chinese", "Spanish", "French", "German", "Japanese", "100+ languages"],
    openSource: false,
    pricing: "Free tier / from $4.99/mo Premium",
    pricingZh: "免费版 / 从 $4.99/月 Premium",
    pricingTiers: [
      {
        tier: "Free",
        tierZh: "免费版",
        price: "$0",
        features: ["25 credits/month", "Basic features", "Express access"],
        featuresZh: ["25 积分/月", "基础功能", "Express 访问"],
      },
      {
        tier: "Premium",
        tierZh: "Premium 版",
        price: "$4.99/mo",
        features: ["100 credits/month", "Full features", "Commercial use"],
        featuresZh: ["100 积分/月", "全部功能", "商业使用"],
      },
      {
        tier: "Creative Cloud",
        tierZh: "Creative Cloud",
        price: "Included with CC subscription",
        features: ["Integrated in Photoshop", "Generative Fill", "Generative Expand"],
        featuresZh: ["集成在 Photoshop 中", "生成式填充", "生成式扩展"],
      },
    ],
    strengths: [
      "Deep integration with Adobe professional tools",
      "Commercially safe with licensed training data",
      "Generative Fill and Expand in Photoshop are best-in-class",
      "Enterprise-grade security and compliance",
    ],
    strengthsZh: [
      "与 Adobe 专业工具深度集成",
      "使用授权训练数据，商业安全",
      "Photoshop 中的生成式填充和扩展业界领先",
      "企业级安全性和合规性",
    ],
    weaknesses: [
      "Requires Creative Cloud subscription",
      "Limited free credits per month",
      "Less creative freedom than open-source alternatives",
      "Locked into Adobe ecosystem",
    ],
    weaknessesZh: [
      "需要 Creative Cloud 订阅",
      "每月免费积分有限",
      "创意自由度不如开源替代方案",
      "锁定在 Adobe 生态中",
    ],
    bestFor: [
      "Professional photo editing with Generative Fill",
      "Commercial design workflows in Creative Cloud",
      "Brand-accurate marketing asset generation",
      "Enterprise design teams needing compliance",
    ],
    bestForZh: [
      "使用生成式填充的专业照片编辑",
      "Creative Cloud 中的商业设计工作流",
      "品牌精准的营销素材生成",
      "需要合规性的企业设计团队",
    ],
    url: "https://www.adobe.com/products/firefly.html",
    icon: "\u{1F525}",
  },

  // ========================================
  // Video Generation (3)
  // ========================================
  {
    id: "sora",
    name: "Sora",
    nameZh: "Sora",
    developer: "OpenAI",
    developerZh: "OpenAI",
    releaseDate: "2025",
    category: "video-generation",
    description: "OpenAI's video generation model creating realistic and imaginative scenes from text.",
    descriptionZh: "OpenAI 的视频生成模型，根据文本创建逼真且富有想象力的场景。",
    descriptionLong: "Sora is OpenAI's groundbreaking video generation model that creates realistic and imaginative scenes from text descriptions. It can generate videos up to 60 seconds in length with impressive consistency, realistic physics, and detailed environments. Sora understands how objects interact in the physical world, maintaining spatial and temporal consistency throughout the generated video. It supports generation from text, images, and video inputs, with capabilities including video editing, extension, and looping. Sora represents a major leap in AI video generation, opening possibilities for filmmakers, content creators, and visual storytellers.",
    descriptionLongZh: "Sora 是 OpenAI 突破性的视频生成模型，能够根据文本描述创建逼真且富有想象力的场景。它可以生成长达 60 秒的视频，具有令人印象深刻的连贯性、逼真的物理效果和详细的环境。Sora 理解物体在物理世界中的交互方式，在整个生成的视频中保持空间和时间一致性。它支持从文本、图像和视频输入生成，包括视频编辑、扩展和循环功能。Sora 代表了 AI 视频生成的重大飞跃。",
    parameters: "Undisclosed (estimated ~3B diffusion transformer)",
    contextWindow: "N/A",
    modalities: ["text", "image", "video"],
    languages: ["English"],
    openSource: false,
    pricing: "Included with ChatGPT Plus/Pro",
    pricingZh: "包含在 ChatGPT Plus/Pro 中",
    pricingTiers: [
      {
        tier: "ChatGPT Plus",
        tierZh: "ChatGPT Plus",
        price: "$20/mo",
        features: ["Limited Sora generations", "720p resolution", "5-second clips"],
        featuresZh: ["有限 Sora 生成", "720p 分辨率", "5 秒片段"],
      },
      {
        tier: "ChatGPT Pro",
        tierZh: "ChatGPT Pro",
        price: "$200/mo",
        features: ["Unlimited Sora", "1080p resolution", "20-second clips", "Priority queue"],
        featuresZh: ["无限 Sora 生成", "1080p 分辨率", "20 秒片段", "优先队列"],
      },
    ],
    strengths: [
      "Unprecedented video quality and realism from text",
      "Consistent physics and object interaction",
      "Supports multiple input types (text, image, video)",
      "Video editing and extension capabilities",
    ],
    strengthsZh: [
      "前所未有的视频质量和真实感",
      "一致的物理效果和物体交互",
      "支持多种输入类型（文本、图像、视频）",
      "视频编辑和扩展能力",
    ],
    weaknesses: [
      "Limited availability outside ChatGPT",
      "Expensive Pro tier for full access",
      "Still has occasional physical inconsistencies",
      "No public API yet",
    ],
    weaknessesZh: [
      "ChatGPT 之外可用性有限",
      "完整使用需昂贵的 Pro 订阅",
      "偶尔出现物理不一致",
      "尚未提供公开 API",
    ],
    bestFor: [
      "Creating short films and cinematic content",
      "Visual storytelling and concept visualization",
      "Social media video content creation",
      "Rapid video prototyping and ideation",
    ],
    bestForZh: [
      "创作短片和电影级内容",
      "视觉叙事和概念可视化",
      "社交媒体视频内容创作",
      "快速视频原型和构思",
    ],
    url: "https://openai.com/sora",
    icon: "\u{1F3AC}",
  },
  {
    id: "runway-gen-3",
    name: "Runway Gen-3",
    nameZh: "Runway Gen-3",
    developer: "Runway ML",
    developerZh: "Runway ML",
    releaseDate: "2024-06",
    category: "video-generation",
    description: "Professional AI video generation with advanced motion control and editing tools.",
    descriptionZh: "专业级 AI 视频生成，具备高级运动控制和编辑工具。",
    descriptionLong: "Runway Gen-3 Alpha is a professional AI video generation model offering text-to-video, image-to-video, and video-to-video generation with advanced motion control. It features significantly improved consistency, motion realism, and resolution compared to earlier versions. Gen-3 includes professional editing capabilities like in-painting, motion tracking, green screen removal, and a timeline-based editor. Used by filmmakers, content creators, and studios, Runway provides a comprehensive video production platform with real-time collaboration features and 4K export capabilities.",
    descriptionLongZh: "Runway Gen-3 Alpha 是一款专业 AI 视频生成模型，提供文本转视频、图像转视频和视频转视频生成，并具备高级运动控制。与前代相比，它在连贯性、运动真实感和分辨率方面有显著提升。Gen-3 包括专业编辑功能，如图像修复、运动追踪、绿幕移除和基于时间线的编辑器。Runway 被电影制作人、内容创作者和工作室广泛使用。",
    parameters: "Undisclosed",
    contextWindow: "N/A",
    modalities: ["text", "image", "video"],
    languages: ["English"],
    openSource: false,
    pricing: "Free tier / from $15/mo",
    pricingZh: "免费版 / 从 $15/月",
    pricingTiers: [
      {
        tier: "Free",
        tierZh: "免费版",
        price: "$0",
        features: ["Limited generations", "720p export", "Watermark"],
        featuresZh: ["有限生成", "720p 导出", "水印"],
      },
      {
        tier: "Pro",
        tierZh: "Pro 版",
        price: "$15/mo",
        features: ["Unlimited generations", "4K export", "Green screen", "No watermark"],
        featuresZh: ["无限生成", "4K 导出", "绿幕", "无水印"],
      },
      {
        tier: "Team",
        tierZh: "团队版",
        price: "$30/mo",
        features: ["All Pro features", "Collaboration", "Priority support"],
        featuresZh: ["所有 Pro 功能", "协作功能", "优先支持"],
      },
    ],
    strengths: [
      "High-quality video generation with realistic motion",
      "Comprehensive editing toolset beyond generation",
      "Multiple generation modes (text, image, video-to-video)",
      "Professional-grade export at 4K resolution",
    ],
    strengthsZh: [
      "高质量视频生成，运动效果真实",
      "超越生成本身的全面编辑工具集",
      "多种生成模式（文本、图像、视频转视频）",
      "4K 分辨率专业级导出",
    ],
    weaknesses: [
      "Pro plans can be expensive for heavy users",
      "Learning curve for advanced editing features",
      "Generation quality varies across different scenes",
    ],
    weaknessesZh: [
      "重度用户使用 Pro 计划成本较高",
      "高级编辑功能学习曲线较陡",
      "不同场景下生成质量参差不齐",
    ],
    bestFor: [
      "Professional video production and short films",
      "Social media content with high production value",
      "Video editing with AI-powered tools",
      "Motion graphics and visual effects",
    ],
    bestForZh: [
      "专业视频制作和短片创作",
      "高质量社交媒体内容",
      "AI 驱动的视频编辑",
      "动态图形和视觉效果",
    ],
    url: "https://runwayml.com",
    icon: "\u{1F39E}️",
  },
  {
    id: "kling-2-0",
    name: "Kling 2.0",
    nameZh: "可灵 2.0",
    developer: "Kuaishou Technology",
    developerZh: "快手科技",
    releaseDate: "2025",
    category: "video-generation",
    description: "Advanced AI video generation with realistic physics, motion, and extended duration.",
    descriptionZh: "先进的 AI 视频生成，逼真的物理效果、运动轨迹和更长的生成时长。",
    descriptionLong: "Kling 2.0 is Kuaishou's next-generation AI video generation model, building on the success of the original Kling model. It features significantly improved video quality, longer generation durations, and more realistic physics and motion. Kling 2.0 excels at generating videos with complex scenes, multiple objects, and natural motion trajectories. It supports text-to-video and image-to-video generation with advanced controls for camera movement and style. The model's strong performance in realistic video generation has made it a leading competitor to Sora and Runway.",
    descriptionLongZh: "可灵 2.0 是快手科技的新一代 AI 视频生成模型，在第一代可灵的成功基础上大幅提升了视频质量、生成长度和物理真实感。可灵 2.0 擅长生成复杂场景、多物体和自然运动轨迹的视频。它支持文本转视频和图像转视频生成，提供摄像机运动和风格的进阶控制。该模型在逼真视频生成方面的强劲表现使其成为 Sora 和 Runway 的主要竞争对手。",
    parameters: "Undisclosed",
    contextWindow: "N/A",
    modalities: ["text", "image", "video"],
    languages: ["Chinese", "English"],
    openSource: false,
    pricing: "Free tier / from ~$10/mo",
    pricingZh: "免费版 / 从约 $10/月",
    pricingTiers: [
      {
        tier: "Free",
        tierZh: "免费版",
        price: "$0",
        features: ["Limited generations", "Standard quality", "Watermark"],
        featuresZh: ["有限生成", "标准质量", "水印"],
      },
      {
        tier: "Pro",
        tierZh: "Pro 版",
        price: "~$10/mo",
        features: ["More generations", "HD quality", "No watermark", "Faster queue"],
        featuresZh: ["更多生成次数", "高清质量", "无水印", "更快排队"],
      },
    ],
    strengths: [
      "Realistic physics and natural motion",
      "Longer video generation duration",
      "Strong performance with complex scenes",
      "Good text-to-video quality at competitive price",
    ],
    strengthsZh: [
      "逼真的物理效果和自然运动",
      "更长的视频生成时长",
      "复杂场景下表现优秀",
      "性价比高的文本转视频质量",
    ],
    weaknesses: [
      "Less global availability than competitors",
      "Smaller international community",
      "Some features only in Chinese",
      "Limited editing tools compared to Runway",
    ],
    weaknessesZh: [
      "全球可用性不如竞争对手",
      "国际社区较小",
      "部分功能仅支持中文",
      "编辑工具不如 Runway 丰富",
    ],
    bestFor: [
      "Realistic video generation with complex scenes",
      "Chinese-language video content creation",
      "Short-form video and social media content",
      "Cost-effective AI video generation",
    ],
    bestForZh: [
      "复杂场景的逼真视频生成",
      "中文视频内容创作",
      "短视频和社交媒体内容",
      "性价比高的 AI 视频生成",
    ],
    url: "https://kling.kuaishou.com",
    icon: "\u{1F4FD}️",
  },

  // ========================================
  // Code (3)
  // ========================================
  {
    id: "claude-code",
    name: "Claude Code",
    nameZh: "Claude Code",
    developer: "Anthropic",
    developerZh: "Anthropic",
    releaseDate: "2025",
    category: "code",
    description: "Anthropic's agentic coding tool for terminal-based AI-assisted software development.",
    descriptionZh: "Anthropic 的智能编码工具，终端中的 AI 辅助软件开发助手。",
    descriptionLong: "Claude Code is Anthropic's agentic coding tool that operates directly in the terminal. Unlike traditional AI coding assistants, Claude Code has full file system access, can execute commands, manage git operations, and handle complex multi-file refactoring tasks autonomously. It understands entire codebases, provides deep contextual awareness, and can plan and execute multi-step development tasks. Claude Code excels at code generation, debugging, refactoring, code review, and documentation. It represents a new paradigm in AI-assisted development where the AI acts as an autonomous engineering partner rather than just a code completion tool.",
    descriptionLongZh: "Claude Code 是 Anthropic 的智能编码工具，直接在终端中运行。与传统 AI 编码助手不同，Claude Code 拥有完整的文件系统访问权限，可以执行命令、管理 git 操作，并能自主处理复杂的多文件重构任务。它能理解整个代码库，提供深度的上下文感知能力，并可以规划和执行多步骤的开发任务。Claude Code 在代码生成、调试、重构、代码审查和文档编写方面表现出色。它代表了 AI 辅助开发的新范式。",
    parameters: "Based on Claude 4 models",
    contextWindow: "200K tokens",
    modalities: ["text"],
    languages: ["English", "Chinese", "50+ languages"],
    openSource: false,
    pricing: "Included with Claude Pro ($20/mo)",
    pricingZh: "包含在 Claude Pro 中（$20/月）",
    pricingTiers: [
      {
        tier: "Claude Pro",
        tierZh: "Claude Pro",
        price: "$20/mo",
        features: ["Claude Code access", "File system operations", "Git integration"],
        featuresZh: ["Claude Code 访问", "文件系统操作", "Git 集成"],
      },
      {
        tier: "Claude Team",
        tierZh: "Claude Team",
        price: "$30/user/mo",
        features: ["All Pro features", "Shared projects", "Higher rate limits"],
        featuresZh: ["所有 Pro 功能", "共享项目", "更高速率限制"],
      },
    ],
    strengths: [
      "Full file system and command execution capability",
      "Deep codebase understanding and contextual awareness",
      "Autonomous multi-file refactoring and planning",
      "Native terminal integration for developers",
    ],
    strengthsZh: [
      "完整的文件系统和命令执行能力",
      "深度代码库理解和上下文感知",
      "自主的多文件重构和规划",
      "原生命令行集成，适合开发者",
    ],
    weaknesses: [
      "Requires terminal comfort and CLI knowledge",
      "No GUI interface for non-developers",
      "Can make mistakes when operating on large codebases",
    ],
    weaknessesZh: [
      "需要熟悉终端和命令行操作",
      "非开发者没有图形界面",
      "在大型代码库上操作时可能出错",
    ],
    bestFor: [
      "Full-stack development and multi-file refactoring",
      "Bug fixing and code debugging",
      "Code review and documentation generation",
      "Complex development tasks requiring planning",
    ],
    bestForZh: [
      "全栈开发和多文件重构",
      "Bug 修复和代码调试",
      "代码审查和文档生成",
      "需要规划的复杂开发任务",
    ],
    url: "https://claude.ai",
    apiUrl: "https://api.anthropic.com",
    icon: "\u{2328}️",
  },
  {
    id: "gpt-4o-code-interpreter",
    name: "GPT-4o Code Interpreter",
    nameZh: "GPT-4o Code Interpreter",
    developer: "OpenAI",
    developerZh: "OpenAI",
    releaseDate: "2024-05",
    category: "code",
    description: "Python code execution environment integrated into ChatGPT for data analysis and programming.",
    descriptionZh: "ChatGPT 中集成的 Python 代码执行环境，用于数据分析和编程。",
    descriptionLong: "GPT-4o Code Interpreter is a powerful feature within ChatGPT that provides a secure, sandboxed Python execution environment. It enables users to analyze data, create visualizations, run statistical tests, and process files using natural language instructions. The code interpreter can handle CSV, Excel, JSON, image, and audio files, generating charts, graphs, and formatted outputs. It automatically writes, executes, and iterates on Python code based on user requests, making data analysis accessible to non-programmers while being powerful enough for experienced data scientists.",
    descriptionLongZh: "GPT-4o Code Interpreter 是 ChatGPT 中的一个强大功能，提供安全的沙箱化 Python 执行环境。用户可以通过自然语言指令分析数据、创建可视化、运行统计测试和处理文件。代码解释器可以处理 CSV、Excel、JSON、图像和音频文件，生成图表和格式化输出。它根据用户请求自动编写、执行和迭代 Python 代码，使非程序员也能进行数据分析，同时对经验丰富的数据科学家来说也足够强大。",
    parameters: "Based on GPT-4o",
    contextWindow: "128K tokens",
    modalities: ["text", "image", "code"],
    languages: ["English", "Chinese", "50+ languages"],
    openSource: false,
    pricing: "Included with ChatGPT Plus ($20/mo)",
    pricingZh: "包含在 ChatGPT Plus 中（$20/月）",
    pricingTiers: [
      {
        tier: "ChatGPT Free",
        tierZh: "ChatGPT 免费版",
        price: "$0",
        features: ["Limited Code Interpreter access", "Basic analysis"],
        featuresZh: ["有限代码解释器访问", "基础分析"],
      },
      {
        tier: "ChatGPT Plus",
        tierZh: "ChatGPT Plus",
        price: "$20/mo",
        features: ["Unlimited Code Interpreter", "File uploads (100MB+)", "Advanced visualization"],
        featuresZh: ["无限代码解释器", "文件上传（100MB+）", "高级可视化"],
      },
    ],
    strengths: [
      "Natural language to Python code translation",
      "Rich data visualization capabilities",
      "Secure sandboxed execution environment",
      "Handles multiple file formats seamlessly",
    ],
    strengthsZh: [
      "自然语言转 Python 代码",
      "丰富的数据可视化能力",
      "安全的沙箱执行环境",
      "无缝处理多种文件格式",
    ],
    weaknesses: [
      "Limited to Python standard library and common packages",
      "No internet access during execution",
      "Execution time and file size limits",
      "Not suitable for production code deployment",
    ],
    weaknessesZh: [
      "限于 Python 标准库和常见包",
      "执行期间无法访问互联网",
      "执行时间和文件大小有限制",
      "不适合生产代码部署",
    ],
    bestFor: [
      "Data analysis and statistical modeling",
      "Creating charts and data visualizations",
      "Processing CSV, Excel, and JSON files",
      "Rapid prototyping and data exploration",
    ],
    bestForZh: [
      "数据分析和统计建模",
      "创建图表和数据可视化",
      "处理 CSV、Excel 和 JSON 文件",
      "快速原型开发和数据探索",
    ],
    url: "https://chat.openai.com",
    icon: "\u{1F4CA}",
  },
  {
    id: "codellama-70b",
    name: "CodeLlama 70B",
    nameZh: "CodeLlama 70B",
    developer: "Meta AI",
    developerZh: "Meta AI",
    releaseDate: "2024-01",
    category: "open-source",
    description: "Open-source code generation model specialized for programming tasks across multiple languages.",
    descriptionZh: "开源代码生成模型，专注于多语言编程任务。",
    descriptionLong: "CodeLlama 70B is Meta's open-source code-specialized large language model, built on Llama 2 with 70 billion parameters. It comes in three variants: Base (general code completion), Python (specialized for Python), and Instruct (fine-tuned for instruction following). CodeLlama 70B supports code generation, completion, debugging, and explanation across popular programming languages. Its open-source nature allows developers to self-host, fine-tune, and integrate it into custom development workflows without API costs or rate limits.",
    descriptionLongZh: "CodeLlama 70B 是 Meta 的开源代码专用大语言模型，基于 Llama 2 构建，拥有 700 亿参数。它提供三个变体：Base（通用代码补全）、Python（Python 专用）和 Instruct（指令跟随优化）。CodeLlama 70B 支持多种流行编程语言的代码生成、补全、调试和解释。其开源特性允许开发者自部署、微调并将其集成到自定义开发工作流中，无需 API 成本或速率限制。",
    parameters: "70B",
    contextWindow: "100K tokens",
    modalities: ["text", "code"],
    languages: ["English", "Chinese", "50+ languages"],
    openSource: true,
    license: "Llama 2 Community License",
    pricing: "Free (open-source)",
    pricingZh: "免费（开源）",
    pricingTiers: [
      {
        tier: "Self-Hosted",
        tierZh: "自部署",
        price: "$0",
        features: ["Full model weights", "Unlimited inference", "Fine-tuning allowed"],
        featuresZh: ["完整模型权重", "无限推理", "支持微调"],
      },
      {
        tier: "API (Together/Perplexity)",
        tierZh: "API（Together/Perplexity）",
        price: "From $0.20/M tokens",
        features: ["Hosted inference", "No GPU needed", "Rate limits"],
        featuresZh: ["托管推理", "无需 GPU", "速率限制"],
      },
    ],
    strengths: [
      "Open-source with permissive licensing",
      "Strong multi-language code generation",
      "Can be self-hosted for privacy and cost savings",
      "Specialized variants for different use cases",
    ],
    strengthsZh: [
      "开源且许可宽松",
      "强大的多语言代码生成能力",
      "可自部署以保护隐私和节省成本",
      "针对不同用例的专门变体",
    ],
    weaknesses: [
      "Requires significant GPU resources to run",
      "Outperformed by newer models (Llama 4, GPT-4o)",
      "No multimodal capabilities",
      "Limited context compared to modern models",
    ],
    weaknessesZh: [
      "需要大量 GPU 资源来运行",
      "被新模型（Llama 4、GPT-4o）超越",
      "不具备多模态能力",
      "上下文长度不如现代模型",
    ],
    bestFor: [
      "Self-hosted code generation and completion",
      "Fine-tuning for domain-specific code tasks",
      "Privacy-sensitive development environments",
      "Offline code assistance without API dependency",
    ],
    bestForZh: [
      "自部署代码生成和补全",
      "针对特定领域代码任务的微调",
      "隐私敏感的开发环境",
      "无需 API 的离线代码辅助",
    ],
    url: "https://github.com/facebookresearch/codellama",
    githubUrl: "https://github.com/facebookresearch/codellama",
    icon: "\u{1F4E6}",
  },

  // ========================================
  // Multimodal (4)
  // ========================================
  {
    id: "gemini-2-5-flash",
    name: "Gemini 2.5 Flash",
    nameZh: "Gemini 2.5 Flash",
    developer: "Google DeepMind",
    developerZh: "Google DeepMind",
    releaseDate: "2025",
    category: "multimodal",
    description: "Google's fast and efficient multimodal model for high-volume, low-latency applications.",
    descriptionZh: "Google 快速高效的多模态模型，适用于大流量、低延迟应用。",
    descriptionLong: "Gemini 2.5 Flash is Google's lightweight multimodal model designed for speed and efficiency while maintaining strong performance. It processes text, images, audio, and video inputs with significantly lower latency than Pro models, making it ideal for real-time applications and high-volume use cases. Despite its smaller size, Gemini 2.5 Flash delivers impressive results on reasoning, coding, and analysis tasks. It features a 1M token context window matching its Pro counterpart, and is available at a fraction of the cost, making it the most cost-effective model in the Gemini family.",
    descriptionLongZh: "Gemini 2.5 Flash 是 Google 的轻量级多模态模型，专为速度和效率设计，同时保持强劲性能。它处理文本、图像、音频和视频输入的延迟显著低于 Pro 模型，非常适合实时应用和大流量场景。尽管体积较小，Gemini 2.5 Flash 在推理、编程和分析任务上仍能提供令人印象深刻的结果。它拥有与 Pro 版本相同的 100 万 token 上下文窗口，成本仅为其零头。",
    parameters: "Undisclosed (lightweight)",
    contextWindow: "1M tokens",
    modalities: ["text", "image", "audio", "video", "code"],
    languages: ["English", "Chinese", "Spanish", "Arabic", "French", "German", "50+ languages"],
    openSource: false,
    pricing: "Free tier / API from $0.15/1M tokens",
    pricingZh: "免费版 / API 从 $0.15/百万 token",
    pricingTiers: [
      {
        tier: "Free",
        tierZh: "免费版",
        price: "$0",
        features: ["Gemini 2.5 Flash", "Google Search", "File uploads"],
        featuresZh: ["Gemini 2.5 Flash", "Google 搜索", "文件上传"],
      },
      {
        tier: "API",
        tierZh: "API",
        price: "From $0.15/1M input tokens",
        features: ["Pay-as-you-go", "1M token context", "Multimodal input"],
        featuresZh: ["按量计费", "100 万 token 上下文", "多模态输入"],
      },
    ],
    strengths: [
      "Fastest response times in Gemini family",
      "1M token context window at low cost",
      "Full multimodal support (text, image, audio, video)",
      "Most cost-effective model for high volume use",
    ],
    strengthsZh: [
      "Gemini 系列中响应速度最快",
      "低成本下的 100 万 token 上下文窗口",
      "完整多模态支持（文本、图像、音频、视频）",
      "大流量场景下性价比最高的模型",
    ],
    weaknesses: [
      "Lower quality than Pro on complex tasks",
      "Less capable at creative writing",
      "May struggle with highly specialized domains",
    ],
    weaknessesZh: [
      "复杂任务上质量不如 Pro",
      "创意写作能力较弱",
      "在高度专业领域可能表现不足",
    ],
    bestFor: [
      "High-throughput real-time applications",
      "Cost-sensitive multimodal processing",
      "Processing large volumes of short content",
      "Applications requiring fast response times",
    ],
    bestForZh: [
      "高吞吐量实时应用",
      "成本敏感的多模态处理",
      "处理大量短内容",
      "需要快速响应的应用",
    ],
    url: "https://gemini.google.com",
    apiUrl: "https://ai.google.dev",
    icon: "\u{26A1}",
  },
  {
    id: "gpt-4v",
    name: "GPT-4V",
    nameZh: "GPT-4V",
    developer: "OpenAI",
    developerZh: "OpenAI",
    releaseDate: "2023-09",
    category: "multimodal",
    description: "OpenAI's first vision model integrating image understanding into conversational AI.",
    descriptionZh: "OpenAI 的首个视觉模型，将图像理解融入对话式 AI。",
    descriptionLong: "GPT-4V (Vision) is OpenAI's pioneering multimodal model that added image understanding capabilities to GPT-4. It can analyze photos, screenshots, documents, and diagrams, answering questions about visual content with detailed reasoning. GPT-4V introduced capabilities like reading handwritten text, identifying objects and scenes, analyzing charts and graphs, and providing contextual descriptions of images. As the foundation for later multimodal models, GPT-4V paved the way for GPT-4o and GPT-5's integrated vision capabilities.",
    descriptionLongZh: "GPT-4V（视觉）是 OpenAI 开创性的多模态模型，为 GPT-4 增加了图像理解能力。它可以分析照片、截图、文档和图表，对视觉内容进行详细的推理回答。GPT-4V 引入了阅读手写文字、识别物体和场景、分析图表以及提供图像上下文描述等能力。作为后续多模态模型的基础，GPT-4V 为 GPT-4o 和 GPT-5 的集成视觉能力铺平了道路。",
    parameters: "Estimated ~1.76 trillion (GPT-4 base)",
    contextWindow: "128K tokens",
    modalities: ["text", "image"],
    languages: ["English", "Chinese", "Spanish", "Arabic", "50+ languages"],
    openSource: false,
    pricing: "API $10.00/1M input tokens (vision)",
    pricingZh: "API $10.00/百万输入 token（视觉）",
    pricingTiers: [
      {
        tier: "API",
        tierZh: "API",
        price: "$10.00/1M input tokens",
        features: ["Vision understanding", "128K context", "Text and image input"],
        featuresZh: ["视觉理解", "128K 上下文", "文本和图像输入"],
      },
    ],
    strengths: [
      "Pioneering vision-language understanding",
      "Accurate image description and analysis",
      "Handles diverse visual inputs (photos, diagrams, text)",
      "Strong reasoning about visual content",
    ],
    strengthsZh: [
      "开创性的视觉语言理解能力",
      "准确的图像描述和分析",
      "处理多样化的视觉输入（照片、图表、文字）",
      "对视觉内容的深度推理",
    ],
    weaknesses: [
      "Superseded by GPT-4o's integrated capabilities",
      "Separate model from main GPT-4 (not unified)",
      "Higher cost than newer multimodal models",
      "No audio or video understanding",
    ],
    weaknessesZh: [
      "已被 GPT-4o 的集成能力取代",
      "与主 GPT-4 分离，非统一模型",
      "成本高于更新的多模态模型",
      "不支持音频或视频理解",
    ],
    bestFor: [
      "Image analysis and description tasks",
      "Document and diagram understanding",
      "Visual Q&A and reasoning",
      "OCR and handwriting recognition",
    ],
    bestForZh: [
      "图像分析和描述任务",
      "文档和图表理解",
      "视觉问答和推理",
      "OCR 和手写识别",
    ],
    url: "https://openai.com",
    apiUrl: "https://platform.openai.com",
    icon: "\u{1F441}️",
  },
  {
    id: "claude-3-5-haiku",
    name: "Claude 3.5 Haiku",
    nameZh: "Claude 3.5 Haiku",
    developer: "Anthropic",
    developerZh: "Anthropic",
    releaseDate: "2024-10",
    category: "conversation",
    description: "Anthropic's fastest and most cost-effective model with strong performance and 200K context.",
    descriptionZh: "Anthropic 最快、最具性价比的模型，性能强劲且拥有 200K 上下文。",
    descriptionLong: "Claude 3.5 Haiku is Anthropic's fastest and most affordable model, offering the best price-to-performance ratio in the Claude family. Despite its compact size, it features a full 200K token context window and maintains strong performance on reasoning, coding, analysis, and creative tasks. Haiku is ideal for high-volume applications, real-time chat, content classification, and any scenario requiring fast, cost-effective AI inference. It matches or exceeds the capabilities of much larger models on many standard benchmarks while delivering responses with minimal latency.",
    descriptionLongZh: "Claude 3.5 Haiku 是 Anthropic 最快、最实惠的模型，在 Claude 系列中提供最佳的性价比。尽管体积紧凑，它拥有完整的 200K token 上下文窗口，并在推理、编程、分析和创意任务上保持强劲性能。Haiku 非常适合大流量应用、实时聊天、内容分类以及任何需要快速、高性价比 AI 推理的场景。它在许多标准基准测试上匹配甚至超越更大的模型。",
    parameters: "Undisclosed (lightweight)",
    contextWindow: "200K tokens",
    modalities: ["text", "image"],
    languages: ["English", "Chinese", "Spanish", "Arabic", "French", "German", "50+ languages"],
    openSource: false,
    pricing: "From $0.80/1M input tokens (API)",
    pricingZh: "从 $0.80/百万输入 token（API）",
    pricingTiers: [
      {
        tier: "Free (Claude.ai)",
        tierZh: "免费（Claude.ai）",
        price: "$0",
        features: ["Claude 3.5 Haiku access", "Limited daily messages"],
        featuresZh: ["Claude 3.5 Haiku 访问", "每日有限消息"],
      },
      {
        tier: "API",
        tierZh: "API",
        price: "$0.80/1M input tokens",
        features: ["Pay-as-you-go", "200K context", "Vision support", "Fastest speed"],
        featuresZh: ["按量计费", "200K 上下文", "视觉支持", "最快速度"],
      },
    ],
    strengths: [
      "Fastest inference speed in Claude family",
      "Best price-to-performance ratio",
      "Full 200K context window despite compact size",
      "Excellent for high-volume classification and extraction",
    ],
    strengthsZh: [
      "Claude 系列中最快的推理速度",
      "最高的性价比",
      "紧凑体积下的完整 200K 上下文窗口",
      "非常适合高容量分类和提取任务",
    ],
    weaknesses: [
      "Less capable on complex reasoning than Sonnet/Opus",
      "Lower creative writing quality",
      "Not suitable for deep analytical tasks",
    ],
    weaknessesZh: [
      "复杂推理能力不如 Sonnet/Opus",
      "创意写作质量较低",
      "不适合深度分析任务",
    ],
    bestFor: [
      "High-volume API applications with cost sensitivity",
      "Real-time chat and customer service",
      "Content classification and moderation",
      "Simple extraction and summarization tasks",
    ],
    bestForZh: [
      "成本敏感的大容量 API 应用",
      "实时聊天和客户服务",
      "内容分类和审核",
      "简单的提取和摘要任务",
    ],
    url: "https://claude.ai",
    apiUrl: "https://api.anthropic.com",
    icon: "\u{1F41D}",
  },
  {
    id: "qwen-vl-max",
    name: "Qwen-VL-Max",
    nameZh: "通义千问VL-Max",
    developer: "Alibaba Cloud",
    developerZh: "阿里云",
    releaseDate: "2025",
    category: "multimodal",
    description: "Alibaba's flagship multimodal model with advanced vision-language understanding in Chinese/English.",
    descriptionZh: "阿里云的旗舰多模态模型，中英文视觉语言理解能力领先。",
    descriptionLong: "Qwen-VL-Max is Alibaba Cloud's flagship multimodal large language model, part of the Qwen (通义千问) family. It excels at vision-language understanding tasks including image captioning, visual Q&A, document understanding, and multi-image reasoning. With strong performance in both Chinese and English, Qwen-VL-Max handles complex visual reasoning tasks like chart interpretation, diagram understanding, and detailed image analysis. It is particularly strong in understanding Chinese cultural contexts, documents, and scenes. Available through Alibaba Cloud's API and Tongyi Qianwen web interface.",
    descriptionLongZh: "通义千问VL-Max 是阿里云的旗舰多模态大语言模型，属于通义千问系列。它在视觉语言理解任务上表现出色，包括图像描述、视觉问答、文档理解和多图像推理。Qwen-VL-Max 在中文和英文环境下都有强劲表现，擅长处理图表解读、图表理解和详细图像分析等复杂视觉推理任务。在理解中文文化语境、文档和场景方面尤为出色。",
    parameters: "Undisclosed (estimated ~100B+)",
    contextWindow: "128K tokens",
    modalities: ["text", "image"],
    languages: ["Chinese", "English"],
    openSource: false,
    pricing: "API from ~$0.50/1M tokens",
    pricingZh: "API 从约 $0.50/百万 token",
    pricingTiers: [
      {
        tier: "Free (Web)",
        tierZh: "免费（网页版）",
        price: "$0",
        features: ["Limited Qwen chat", "Basic vision tasks", "File uploads"],
        featuresZh: ["有限通义千问对话", "基础视觉任务", "文件上传"],
      },
      {
        tier: "API",
        tierZh: "API",
        price: "From ~$0.50/1M tokens",
        features: ["Pay-as-you-go", "Vision-language", "128K context"],
        featuresZh: ["按量计费", "视觉语言能力", "128K 上下文"],
      },
    ],
    strengths: [
      "Leading vision-language understanding in Chinese contexts",
      "Strong document and chart analysis",
      "Bilingual proficiency in Chinese and English",
      "Good multi-image reasoning capabilities",
    ],
    strengthsZh: [
      "中文语境下领先的视觉语言理解",
      "强大的文档和图表分析能力",
      "中英双语熟练",
      "良好的多图像推理能力",
    ],
    weaknesses: [
      "Limited availability outside Asia",
      "Smaller global community and ecosystem",
      "Less capable on non-visual reasoning tasks",
    ],
    weaknessesZh: [
      "亚洲以外地区可用性有限",
      "全球社区和生态系统较小",
      "非视觉推理任务能力较弱",
    ],
    bestFor: [
      "Chinese document and image understanding",
      "Bilingual visual Q&A applications",
      "Chinese cultural context analysis",
      "Document digitization and understanding",
    ],
    bestForZh: [
      "中文文档和图像理解",
      "双语视觉问答应用",
      "中国文化语境分析",
      "文档数字化和理解",
    ],
    url: "https://tongyi.aliyun.com",
    apiUrl: "https://help.aliyun.com/document_detail/2712195.html",
    icon: "\u{1F310}",
  },

  // ========================================
  // Open-Source Highlight (3 more)
  // ========================================
  {
    id: "mistral-large-2",
    name: "Mistral Large 2",
    nameZh: "Mistral Large 2",
    developer: "Mistral AI",
    developerZh: "Mistral AI",
    releaseDate: "2024-07",
    category: "open-source",
    description: "Mistral AI's flagship open-weight model with 123B parameters and multilingual excellence.",
    descriptionZh: "Mistral AI 的旗舰开源权重模型，123B 参数，多语言能力出色。",
    descriptionLong: "Mistral Large 2 is Mistral AI's flagship open-weight model with 123 billion parameters. It offers strong performance across reasoning, coding, and multilingual tasks with support for French, German, Spanish, Italian, Portuguese, Arabic, Hindi, Russian, Chinese, Japanese, and Korean. Built with a focus on efficiency, it features a 128K token context window and supports function calling and JSON output. Mistral Large 2 is competitive with GPT-4o and Claude 3.5 Sonnet on many benchmarks while being available under an open-weight license for self-hosting and customization.",
    descriptionLongZh: "Mistral Large 2 是 Mistral AI 的旗舰开源权重模型，拥有 1230 亿参数。它在推理、编程和多语言任务上表现强劲，支持法语、德语、西班牙语、意大利语、葡萄牙语、阿拉伯语、印地语、俄语、中文、日语和韩语。以效率为核心设计理念，拥有 128K token 上下文窗口，支持函数调用和 JSON 输出。Mistral Large 2 在多项基准测试上与 GPT-4o 和 Claude 3.5 Sonnet 竞争。",
    parameters: "123B",
    contextWindow: "128K tokens",
    modalities: ["text"],
    languages: ["English", "French", "German", "Spanish", "Italian", "Portuguese", "Arabic", "Hindi", "Russian", "Chinese", "Japanese", "Korean"],
    openSource: true,
    license: "Mistral Research License (open-weight)",
    pricing: "Free (open-weight) / API from $2.00/1M tokens",
    pricingZh: "免费（开源权重）/ API 从 $2.00/百万 token",
    pricingTiers: [
      {
        tier: "Open Weights",
        tierZh: "开源权重",
        price: "$0",
        features: ["123B parameter model", "Self-hosting", "Research use"],
        featuresZh: ["123B 参数模型", "自部署", "研究使用"],
      },
      {
        tier: "API (Mistral Platform)",
        tierZh: "API（Mistral 平台）",
        price: "From $2.00/1M tokens",
        features: ["Hosted inference", "Commercial use", "Function calling"],
        featuresZh: ["托管推理", "商业使用", "函数调用"],
      },
      {
        tier: "API (Azure/AWS)",
        tierZh: "API（Azure/AWS）",
        price: "Marketplace pricing",
        features: ["Cloud integration", "Enterprise support", "SLA guarantees"],
        featuresZh: ["云集成", "企业支持", "SLA 保障"],
      },
    ],
    strengths: [
      "Exceptional multilingual performance across 12+ languages",
      "Open-weight for self-hosting and customization",
      "Strong coding and reasoning benchmarks",
      "Efficient architecture for its parameter count",
    ],
    strengthsZh: [
      "在 12+ 语言上出色的多语言性能",
      "开源权重，可自部署和定制",
      "强劲的编程和推理基准测试表现",
      "与其参数量相匹配的高效架构",
    ],
    weaknesses: [
      "Text-only model, no vision capabilities",
      "Research license has some restrictions",
      "Smaller ecosystem than Llama models",
    ],
    weaknessesZh: [
      "仅文本模型，无视觉能力",
      "研究许可有一定限制",
      "生态系统不如 Llama 模型",
    ],
    bestFor: [
      "Multilingual AI applications across European languages",
      "Self-hosted enterprise AI with strong reasoning",
      "Function calling and structured output applications",
      "Cost-effective alternative to GPT-4o for text tasks",
    ],
    bestForZh: [
      "跨欧洲语言的多语言 AI 应用",
      "需要强推理能力的自部署企业 AI",
      "函数调用和结构化输出应用",
      "文本任务上 GPT-4o 的性价比替代方案",
    ],
    benchmarks: [
      { name: "MMLU", score: "86.7%", competitor: "Llama 4", competitorScore: "87.1%" },
      { name: "HumanEval", score: "88.4%", competitor: "GPT-4o", competitorScore: "90.2%" },
    ],
    url: "https://mistral.ai",
    apiUrl: "https://console.mistral.ai",
    githubUrl: "https://github.com/mistralai/mistral-inference",
    icon: "\u{1F420}",
  },
  {
    id: "grok-3",
    name: "Grok-3",
    nameZh: "Grok-3",
    developer: "xAI",
    developerZh: "xAI",
    releaseDate: "2025",
    category: "conversation",
    description: "xAI's conversational model with real-time knowledge, humor, and open-weight availability.",
    descriptionZh: "xAI 的对话模型，具备实时知识、幽默风格和开源权重。",
    descriptionLong: "Grok-3 is xAI's latest conversational AI model, building on the Grok series with significant improvements in reasoning, coding, and general knowledge. It features real-time knowledge access through the X (Twitter) platform, giving it up-to-the-minute awareness of global events and trends. Grok-3 is known for its distinctive personality, willingness to answer unconventional questions, and a幽默 tone that sets it apart from more restrained AI assistants. Available to X Premium+ subscribers and through open-weight release for developers.",
    descriptionLongZh: "Grok-3 是 xAI 最新对话 AI 模型，在推理、编程和通用知识方面相比前代有显著提升。它通过 X（Twitter）平台实现实时知识访问，能够获取全球事件和趋势的最新信息。Grok-3 以其独特的个性、愿意回答非常规问题的态度以及幽默风格而著称，这使其与其他更为克制的 AI 助手区别开来。面向 X Premium+ 订阅者，同时也通过开源权重向开发者开放。",
    parameters: "Undisclosed (estimated ~300B)",
    contextWindow: "256K tokens",
    modalities: ["text", "image"],
    languages: ["English", "Chinese", "Spanish", "Arabic", "French", "German", "50+ languages"],
    openSource: true,
    license: "Apache 2.0 (open-weight)",
    pricing: "X Premium+ ($16/mo) / Free tier limited",
    pricingZh: "X Premium+（$16/月）/ 免费版有限",
    pricingTiers: [
      {
        tier: "X Premium+",
        tierZh: "X Premium+",
        price: "$16/mo",
        features: ["Full Grok-3 access", "Real-time X knowledge", "Priority queue"],
        featuresZh: ["完整 Grok-3 访问", "实时 X 平台知识", "优先队列"],
      },
      {
        tier: "Open Weights",
        tierZh: "开源权重",
        price: "$0",
        features: ["Self-hosting", "Research use", "Apache 2.0 license"],
        featuresZh: ["自部署", "研究使用", "Apache 2.0 许可"],
      },
    ],
    strengths: [
      "Real-time knowledge through X platform integration",
      "Distinctive personality and conversational style",
      "Open-weight under permissive Apache 2.0 license",
      "Willingness to engage with unconventional topics",
    ],
    strengthsZh: [
      "通过 X 平台集成实现实时知识",
      "独特的个性和对话风格",
      "在宽松的 Apache 2.0 许可下开源权重",
      "愿意参与非常规话题讨论",
    ],
    weaknesses: [
      "Requires X Premium+ for full access",
      "Personality may not suit all use cases",
      "Smaller ecosystem than established competitors",
      "Less enterprise support and documentation",
    ],
    weaknessesZh: [
      "完整访问需要 X Premium+",
      "个性风格可能不适合所有场景",
      "生态系统不如成熟竞争对手",
      "企业支持和文档较少",
    ],
    bestFor: [
      "Conversational AI with real-time world knowledge",
      "Creative brainstorming and unconventional Q&A",
      "Self-hosted AI with Apache 2.0 license",
      "Social media and trending topics analysis",
    ],
    bestForZh: [
      "具备实时世界知识的对话 AI",
      "创意头脑风暴和非常规问答",
      "基于 Apache 2.0 许可的自部署 AI",
      "社交媒体和热门话题分析",
    ],
    url: "https://grok.com",
    githubUrl: "https://github.com/xai-org/grok-1",
    icon: "\u{1F47E}",
  },
  {
    id: "gemma-3",
    name: "Gemma 3",
    nameZh: "Gemma 3",
    developer: "Google DeepMind",
    developerZh: "Google DeepMind",
    releaseDate: "2025",
    category: "open-source",
    description: "Google's lightweight open-source model family for efficient on-device and edge deployment.",
    descriptionZh: "Google 的轻量级开源模型系列，适用于高效的设备和边缘部署。",
    descriptionLong: "Gemma 3 is Google's lightweight open-source model family, designed for efficient deployment on consumer hardware, mobile devices, and edge environments. Available in 2B and 7B parameter configurations, Gemma 3 delivers strong performance for its size, leveraging Google DeepMind's advanced research in model compression and efficient architecture. It supports text and code generation with an 8K token context window. Gemma 3 is ideal for developers building lightweight AI applications, running inference on-device, or deploying cost-efficient AI at scale. Released under a permissive commercial license, it enables widespread adoption across research and production.",
    descriptionLongZh: "Gemma 3 是 Google 的轻量级开源模型系列，专为在消费级硬件、移动设备和边缘环境中高效部署而设计。提供 2B 和 7B 参数两种配置，Gemma 3 在其尺寸级别上提供了强劲性能，利用了 Google DeepMind 在模型压缩和高效架构方面的高级研究。它支持文本和代码生成，拥有 8K token 上下文窗口。Gemma 3 非常适合构建轻量级 AI 应用、在设备上运行推理或大规模部署成本效益高的 AI。",
    parameters: "2B / 7B",
    contextWindow: "8K tokens",
    modalities: ["text", "code"],
    languages: ["English", "Chinese", "Spanish", "Arabic", "French", "German", "Hindi", "Portuguese", "100+ languages"],
    openSource: true,
    license: "Gemma Commercial License",
    pricing: "Free (open-source)",
    pricingZh: "免费（开源）",
    pricingTiers: [
      {
        tier: "Open Source",
        tierZh: "开源",
        price: "$0",
        features: ["2B and 7B model sizes", "Commercial use", "On-device deployment"],
        featuresZh: ["2B 和 7B 模型大小", "商业使用", "设备端部署"],
      },
      {
        tier: "Google Cloud",
        tierZh: "Google Cloud",
        price: "Pay-per-use",
        features: ["Hosted API", "Vertex AI integration", "Enterprise support"],
        featuresZh: ["托管 API", "Vertex AI 集成", "企业支持"],
      },
    ],
    strengths: [
      "Designed for efficient on-device deployment",
      "Permissive commercial license",
      "Strong performance for its compact size",
      "Multilingual support across 100+ languages",
    ],
    strengthsZh: [
      "专为高效的设备端部署设计",
      "宽松的商业许可",
      "紧凑尺寸下的强劲性能",
      "支持 100+ 语言的多语言能力",
    ],
    weaknesses: [
      "Limited 8K context window",
      "Not suitable for complex reasoning tasks",
      "Significantly less capable than larger models",
    ],
    weaknessesZh: [
      "上下文窗口仅 8K token",
      "不适合复杂推理任务",
      "能力明显不如大型模型",
    ],
    bestFor: [
      "On-device mobile AI applications",
      "Edge computing and IoT deployments",
      "Lightweight text classification and generation",
      "Applications with strict latency and cost requirements",
    ],
    bestForZh: [
      "设备端移动 AI 应用",
      "边缘计算和物联网部署",
      "轻量级文本分类和生成",
      "对延迟和成本有严格要求的应用",
    ],
    url: "https://ai.google.dev/gemma",
    githubUrl: "https://github.com/google/gemma_pytorch",
    icon: "\u{1F48E}",
  },
];
