export interface Tool {
  id: string;
  name: string;
  description: string;
  descriptionEs: string;
  descriptionAr: string;
  category: "chatbots" | "image-generation" | "video-generation" | "writing" | "coding" | "productivity" | "audio" | "learning" | "industry";
  tags: string[];
  difficulty: "beginner" | "intermediate" | "advanced";
  url: string;
  rating: number;
  pricing: string;
  useCase: string;
  icon: string;
}

export const toolCategories = [
  "chatbots",
  "image-generation",
  "video-generation",
  "writing",
  "coding",
  "productivity",
  "audio",
  "learning",
  "industry",
] as const;

export type ToolCategory = (typeof toolCategories)[number];

export const toolCategoryLabels: Record<ToolCategory, { en: string; es: string; ar: string }> = {
  chatbots: { en: "Chatbots", es: "Chatbots", ar: " chatbots" },
  "image-generation": { en: "Image Gen", es: "Generación de Imágenes", ar: "توليد الصور" },
  "video-generation": { en: "Video Gen", es: "Generación de Video", ar: "توليد الفيديو" },
  writing: { en: "Writing", es: "Escritura", ar: "الكتابة" },
  coding: { en: "Coding", es: "Programación", ar: "البرمجة" },
  productivity: { en: "Productivity", es: "Productividad", ar: "الإنتاجية" },
  audio: { en: "Audio", es: "Audio", ar: "الصوت" },
  learning: { en: "Learning", es: "Aprendizaje", ar: "التعلم" },
  industry: { en: "Industry", es: "Industria", ar: "الصناعة" },
};

function r(n: number): number {
  return Math.min(5, Math.max(1, Math.round(n)));
}

export const tools: Tool[] = [
  {
    id: "chatgpt",
    name: "ChatGPT",
    description: "The most popular AI assistant for conversation, writing, coding, and problem-solving.",
    descriptionEs: "El asistente de IA más popular para conversación, escritura, programación y resolución de problemas.",
    descriptionAr: "أشهر مساعد ذكاء اصطناعي للمحادثة والكتابة والبرمجة وحل المشكلات.",
    category: "chatbots",
    tags: ["conversation", "writing", "coding", "analysis"],
    difficulty: "beginner",
    url: "https://chat.openai.com",
    rating: r(4.7),
    pricing: "Free / $20/mo Plus",
    useCase: "ChatGPT handles general Q&A, content drafting, code generation, and brainstorming. Use it as your daily AI copilot for almost any text-based task.",
    icon: "\u{1F916}",
  },
  {
    id: "claude",
    name: "Claude",
    description: "Anthropic's AI assistant focused on safety, long-form reasoning, and detailed analysis.",
    descriptionEs: "El asistente de IA de Anthropic centrado en seguridad, razonamiento extenso y análisis detallado.",
    descriptionAr: "مساعد الذكاء الاصطناعي من Anthropic يركز على الأمان والاستدلال الطويل والتحليل المفصل.",
    category: "chatbots",
    tags: ["reasoning", "analysis", "writing", "safety"],
    difficulty: "beginner",
    url: "https://claude.ai",
    rating: r(4.6),
    pricing: "Free / $20/mo Pro",
    useCase: "Claude excels at long document analysis, detailed writing tasks, and thoughtful reasoning. Great for research, editing, and complex problem-solving.",
    icon: "\u{1F9E0}",
  },
  {
    id: "gemini",
    name: "Google Gemini",
    description: "Google's multimodal AI model with deep Google ecosystem integration.",
    descriptionEs: "El modelo de IA multimodal de Google con integración profunda en el ecosistema Google.",
    descriptionAr: "نموذج الذكاء الاصطناعي متعدد الوسائط من Google مع تكامل عميق مع نظام Google البيئي.",
    category: "chatbots",
    tags: ["multimodal", "google", "reasoning", "search"],
    difficulty: "beginner",
    url: "https://gemini.google.com",
    rating: r(4.5),
    pricing: "Free / $19.99/mo Advanced",
    useCase: "Gemini's multimodal capabilities let you upload images, audio, and video for analysis. It integrates with Google apps like Gmail, Docs, and Drive.",
    icon: "\u{1F31F}",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    description: "Open-source LLM with strong reasoning capabilities and competitive performance.",
    descriptionEs: "LLM de código abierto con sólidas capacidades de razonamiento y rendimiento competitivo.",
    descriptionAr: "نموذج لغوي كبير مفتوح المصدر مع قدرات استدلال قوية وأداء تنافسي.",
    category: "chatbots",
    tags: ["reasoning", "open-source", "coding", "analysis"],
    difficulty: "intermediate",
    url: "https://chat.deepseek.com",
    rating: r(4.4),
    pricing: "Free",
    useCase: "DeepSeek offers strong reasoning and coding capabilities at no cost. Its open-source nature allows self-hosting and customization.",
    icon: "\u{1F50D}",
  },
  {
    id: "perplexity",
    name: "Perplexity AI",
    description: "AI-powered search engine that provides answers with real-time citations.",
    descriptionEs: "Buscador impulsado por IA que proporciona respuestas con citas en tiempo real.",
    descriptionAr: "محرك بحث مدعوم بالذكاء الاصطناعي يقدم إجابات مع استشهادات في الوقت الفعلي.",
    category: "chatbots",
    tags: ["search", "research", "citations", "real-time"],
    difficulty: "beginner",
    url: "https://www.perplexity.ai",
    rating: r(4.5),
    pricing: "Free / $20/mo Pro",
    useCase: "Perplexity is an AI search engine that answers questions with cited sources. Perfect for research, fact-checking, and staying updated.",
    icon: "\u{1F4A1}",
  },
  {
    id: "midjourney",
    name: "Midjourney",
    description: "Leading AI image generator known for artistic quality and stylistic versatility.",
    descriptionEs: "Generador de imágenes IA líder conocido por su calidad artística y versatilidad estilística.",
    descriptionAr: "مولد الصور بالذكاء الاصطناعي الرائد المعروف بجودته الفنية وتنوعه الأسلوبي.",
    category: "image-generation",
    tags: ["art", "design", "creative", "high-quality"],
    difficulty: "intermediate",
    url: "https://www.midjourney.com",
    rating: r(4.8),
    pricing: "$10/mo starting",
    useCase: "Midjourney produces stunning artistic images from text prompts. Best for concept art, illustrations, branding visuals, and creative projects.",
    icon: "\u{1F3A8}",
  },
  {
    id: "dalle3",
    name: "DALL-E 3",
    description: "OpenAI's image generator integrated into ChatGPT with strong prompt adherence.",
    descriptionEs: "Generador de imágenes de OpenAI integrado en ChatGPT con gran fidelidad a las instrucciones.",
    descriptionAr: "مولد الصور من OpenAI المدمج في ChatGPT مع التزام قوي بالتعليمات.",
    category: "image-generation",
    tags: ["openai", "chatgpt", "design", "realistic"],
    difficulty: "beginner",
    url: "https://openai.com/dall-e-3",
    rating: r(4.6),
    pricing: "Included with ChatGPT Plus",
    useCase: "DALL-E 3 generates images directly within ChatGPT. Great for quick visual ideas, social media graphics, and prototyping designs.",
    icon: "\u{1F5BC}️",
  },
  {
    id: "stable-diffusion",
    name: "Stable Diffusion",
    description: "Open-source image generation model with full local control and customization.",
    descriptionEs: "Modelo de generación de imágenes de código abierto con control local y personalización total.",
    descriptionAr: "نموذج توليد الصور مفتوح المصدر مع تحكم محلي كامل وتخصيص.",
    category: "image-generation",
    tags: ["open-source", "local", "customizable", "free"],
    difficulty: "advanced",
    url: "https://stability.ai",
    rating: r(4.4),
    pricing: "Free (open-source)",
    useCase: "Stable Diffusion runs locally on your hardware with full control. Ideal for developers, researchers, and anyone needing uncensored or customized generation.",
    icon: "\u{26A1}",
  },
  {
    id: "adobe-firefly",
    name: "Adobe Firefly",
    description: "Adobe's generative AI suite integrated with Creative Cloud for professional design.",
    descriptionEs: "Suite de IA generativa de Adobe integrada con Creative Cloud para diseño profesional.",
    descriptionAr: "مجموعة الذكاء الاصطناعي التوليدي من Adobe المدمجة مع Creative Cloud للتصميم الاحترافي.",
    category: "image-generation",
    tags: ["adobe", "design", "professional", "integration"],
    difficulty: "intermediate",
    url: "https://www.adobe.com/products/firefly.html",
    rating: r(4.3),
    pricing: "Free tier / Creative Cloud subscription",
    useCase: "Firefly integrates AI image generation into Adobe's design tools. Best for designers who already use Photoshop, Illustrator, or Express.",
    icon: "\u{1F525}",
  },
  {
    id: "leonardo-ai",
    name: "Leonardo AI",
    description: "AI image generation platform with fine-tuned models for games, characters, and assets.",
    descriptionEs: "Plataforma de generación de imágenes IA con modelos ajustados para juegos, personajes y activos.",
    descriptionAr: "منصة توليد الصور بالذكاء الاصطناعي بنماذج مضبوطة للألعاب والشخصيات والأصول.",
    category: "image-generation",
    tags: ["gaming", "assets", "characters", "models"],
    difficulty: "intermediate",
    url: "https://leonardo.ai",
    rating: r(4.4),
    pricing: "Free tier / from $10/mo",
    useCase: "Leonardo AI offers specialized models for game assets, character design, and environment art. Great for indie game developers and content creators.",
    icon: "\u{1F58C}️",
  },
  {
    id: "runway",
    name: "Runway",
    description: "Professional AI video generation and editing platform with advanced motion control.",
    descriptionEs: "Plataforma profesional de generación y edición de video con IA y control avanzado de movimiento.",
    descriptionAr: "منصة احترافية لتوليد وتحرير الفيديو بالذكاء الاصطناعي مع تحكم متقدم في الحركة.",
    category: "video-generation",
    tags: ["video", "editing", "motion", "professional"],
    difficulty: "intermediate",
    url: "https://runwayml.com",
    rating: r(4.5),
    pricing: "Free tier / from $15/mo",
    useCase: "Runway generates and edits video using AI. Use it for creating short films, social media clips, and professional video content with text prompts.",
    icon: "\u{1F3AC}",
  },
  {
    id: "pika",
    name: "Pika",
    description: "Easy-to-use AI video generator focused on quick, high-quality video creation.",
    descriptionEs: "Generador de video IA fácil de usar centrado en la creación rápida de videos de alta calidad.",
    descriptionAr: "مولد فيديو بالذكاء الاصطناعي سهل الاستخدام يركز على إنشاء فيديوهات عالية الجودة بسرعة.",
    category: "video-generation",
    tags: ["video", "quick", "social-media", "easy"],
    difficulty: "beginner",
    url: "https://pika.art",
    rating: r(4.3),
    pricing: "Free tier / from $10/mo",
    useCase: "Pika makes AI video generation accessible to everyone. Great for creating short video clips, animations, and social media content from text prompts.",
    icon: "\u{1F3A5}",
  },
  {
    id: "heygen",
    name: "HeyGen",
    description: "AI video platform for creating talking avatars and professional presentations.",
    descriptionEs: "Plataforma de video IA para crear avatares parlantes y presentaciones profesionales.",
    descriptionAr: "منصة فيديو بالذكاء الاصطناعي لإنشاء صور رمزية متحدثة وعروض تقديمية احترافية.",
    category: "video-generation",
    tags: ["avatars", "presentation", "talking", "business"],
    difficulty: "intermediate",
    url: "https://www.heygen.com",
    rating: r(4.4),
    pricing: "Free tier / from $29/mo",
    useCase: "HeyGen creates talking-head videos from text or scripts using realistic avatars. Perfect for training videos, marketing content, and global communications.",
    icon: "\u{1F3AD}",
  },
  {
    id: "jasper",
    name: "Jasper AI",
    description: "AI writing assistant built for marketing teams and content creators.",
    descriptionEs: "Asistente de escritura IA diseñado para equipos de marketing y creadores de contenido.",
    descriptionAr: "مساعد كتابة بالذكاء الاصطناعي مصمم لفرق التسويق ومنشئي المحتوى.",
    category: "writing",
    tags: ["marketing", "content", "copywriting", "brand"],
    difficulty: "beginner",
    url: "https://www.jasper.ai",
    rating: r(4.3),
    pricing: "from $49/mo",
    useCase: "Jasper specializes in marketing copy, blog posts, and brand content. It uses brand voice customization to produce consistent on-brand writing.",
    icon: "\u{270D}️",
  },
  {
    id: "copy-ai",
    name: "Copy.ai",
    description: "AI copywriting tool for sales, marketing, and social media content.",
    descriptionEs: "Herramienta de copywriting IA para ventas, marketing y contenido de redes sociales.",
    descriptionAr: "أداة كتابة إعلانات بالذكاء الاصطناعي للمبيعات والتسويق ومحتوى وسائل التواصل الاجتماعي.",
    category: "writing",
    tags: ["copywriting", "sales", "marketing", "social-media"],
    difficulty: "beginner",
    url: "https://www.copy.ai",
    rating: r(4.2),
    pricing: "Free tier / from $36/mo",
    useCase: "Copy.ai generates sales copy, email campaigns, and social media posts quickly. Ideal for marketers who need批量 content fast without sacrificing quality.",
    icon: "\u{1F4DD}",
  },
  {
    id: "notion-ai",
    name: "Notion AI",
    description: "AI-powered writing and knowledge management integrated into Notion workspaces.",
    descriptionEs: "Escritura impulsada por IA y gestión del conocimiento integrada en espacios de trabajo Notion.",
    descriptionAr: "الكتابة المدعومة بالذكاء الاصطناعي وإدارة المعرفة المدمجة في مساحات عمل Notion.",
    category: "productivity",
    tags: ["notes", "knowledge", "writing", "organization"],
    difficulty: "beginner",
    url: "https://www.notion.so/product/ai",
    rating: r(4.5),
    pricing: "$10/mo add-on to Notion plan",
    useCase: "Notion AI assists with drafting, summarizing, and editing inside your Notion workspace. Use it for meeting notes, project docs, and knowledge base articles.",
    icon: "\u{1F4CB}",
  },
  {
    id: "grammarly",
    name: "Grammarly",
    description: "AI writing assistant for grammar checking, style improvement, and tone adjustment.",
    descriptionEs: "Asistente de escritura IA para corrección gramatical, mejora de estilo y ajuste de tono.",
    descriptionAr: "مساعد كتابة بالذكاء الاصطناعي للتدقيق النحوي وتحسين الأسلوب وضبط النبرة.",
    category: "writing",
    tags: ["grammar", "writing", "editing", "style"],
    difficulty: "beginner",
    url: "https://www.grammarly.com",
    rating: r(4.6),
    pricing: "Free / $12/mo Premium",
    useCase: "Grammarly checks grammar, clarity, engagement, and delivery across emails, documents, and web forms. Essential for professional and error-free writing.",
    icon: "\u{2705}",
  },
  {
    id: "cursor",
    name: "Cursor",
    description: "AI-first code editor built on VS Code with deep AI integration for faster development.",
    descriptionEs: "Editor de código con IA basado en VS Code con integración profunda de IA para desarrollo más rápido.",
    descriptionAr: "محرر أكواد يعتمد على الذكاء الاصطناعي مبني على VS Code مع تكامل عميق للذكاء الاصطناعي لتطوير أسرع.",
    category: "coding",
    tags: ["ide", "code-generation", "vs-code", "productivity"],
    difficulty: "intermediate",
    url: "https://cursor.sh",
    rating: r(4.7),
    pricing: "Free / $20/mo Pro",
    useCase: "Cursor is an AI-native code editor that understands your codebase. It offers autocomplete, inline editing, and chat-based code generation.",
    icon: "\u{1F4BB}",
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    description: "AI pair programmer from GitHub that suggests code in real-time across popular IDEs.",
    descriptionEs: "Programador par IA de GitHub que sugiere código en tiempo real en IDEs populares.",
    descriptionAr: "مبرمج زوجي بالذكاء الاصطناعي من GitHub يقترح الأكواد في الوقت الفعلي عبر بيئات التطوير الشهيرة.",
    category: "coding",
    tags: ["code-generation", "ide", "github", "pair-programming"],
    difficulty: "intermediate",
    url: "https://github.com/features/copilot",
    rating: r(4.6),
    pricing: "Free / $10/mo Individual",
    useCase: "Copilot provides real-time code suggestions as you type. It integrates with VS Code, JetBrains, and Neovim for seamless AI-assisted development.",
    icon: "\u{1F91D}",
  },
  {
    id: "replit-ai",
    name: "Replit AI",
    description: "Browser-based IDE with built-in AI agent that can build and deploy apps from prompts.",
    descriptionEs: "IDE basado en navegador con agente IA integrado que puede construir y desplegar apps desde instrucciones.",
    descriptionAr: "بيئة تطوير متكاملة في المتصفح مع وكيل ذكاء اصطناعي مدمج يمكنه بناء ونشر التطبيقات من التعليمات.",
    category: "coding",
    tags: ["ide", "deploy", "no-setup", "agent"],
    difficulty: "beginner",
    url: "https://replit.com",
    rating: r(4.3),
    pricing: "Free / $20/mo Pro",
    useCase: "Replit AI can generate entire applications from a prompt, run them in the browser, and deploy them. Great for prototyping and learning to code.",
    icon: "\u{1F527}",
  },
  {
    id: "gamma",
    name: "Gamma",
    description: "AI-powered presentation tool that creates slides, documents, and web pages from text.",
    descriptionEs: "Herramienta de presentaciones IA que crea diapositivas, documentos y páginas web desde texto.",
    descriptionAr: "أداة عروض تقديمية بالذكاء الاصطناعي تنشئ شرائح ومستندات وصفحات ويب من النص.",
    category: "productivity",
    tags: ["presentation", "slides", "design", "documents"],
    difficulty: "beginner",
    url: "https://gamma.app",
    rating: r(4.5),
    pricing: "Free tier / from $10/mo",
    useCase: "Gamma generates beautiful presentations, documents, and web pages from a simple text prompt. Perfect for students, educators, and business professionals.",
    icon: "\u{1F4CA}",
  },
  {
    id: "beautiful-ai",
    name: "Beautiful.ai",
    description: "AI presentation tool with smart templates that auto-layout your content beautifully.",
    descriptionEs: "Herramienta de presentaciones IA con plantillas inteligentes que maquetan tu contenido automáticamente.",
    descriptionAr: "أداة عروض تقديمية بالذكاء الاصطناعي مع قوالب ذكية تقوم تلقائياً بتنسيق المحتوى الخاص بك بشكل جميل.",
    category: "productivity",
    tags: ["presentation", "design", "templates", "business"],
    difficulty: "beginner",
    url: "https://www.beautiful.ai",
    rating: r(4.2),
    pricing: "from $12/mo",
    useCase: "Beautiful.ai's smart slides auto-arrange your content into professional layouts. Best for business presentations where design consistency matters.",
    icon: "✨",
  },
  {
    id: "canva-ai",
    name: "Canva AI",
    description: "All-in-one design platform with AI features for generating images, copy, and layouts.",
    descriptionEs: "Plataforma de diseño integral con funciones IA para generar imágenes, texto y diseños.",
    descriptionAr: "منصة تصميم شاملة مع ميزات الذكاء الاصطناعي لتوليد الصور والنصوص والتخطيطات.",
    category: "productivity",
    tags: ["design", "templates", "social-media", "all-in-one"],
    difficulty: "beginner",
    url: "https://www.canva.com",
    rating: r(4.7),
    pricing: "Free / $12.99/mo Pro",
    useCase: "Canva AI includes Magic Design, Magic Write, and AI image generation. Ideal for non-designers creating social media graphics, flyers, and presentations.",
    icon: "\u{1F3AF}",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    description: "Industry-leading AI voice synthesis with realistic, expressive speech generation.",
    descriptionEs: "Síntesis de voz IA líder en la industria con generación de voz realista y expresiva.",
    descriptionAr: "توليف صوتي بالذكاء الاصطناعي رائد في الصناعة مع توليد كلام واقعي ومعبّر.",
    category: "audio",
    tags: ["voice", "tts", "audiobooks", "realistic"],
    difficulty: "beginner",
    url: "https://elevenlabs.io",
    rating: r(4.7),
    pricing: "Free tier / from $5/mo",
    useCase: "ElevenLabs generates ultra-realistic speech from text, supports voice cloning, and multi-language narration. Perfect for audiobooks, videos, and voiceovers.",
    icon: "\u{1F399}️",
  },
  {
    id: "suno",
    name: "Suno",
    description: "AI music generation that creates original songs with lyrics from text prompts.",
    descriptionEs: "Generación de música IA que crea canciones originales con letras a partir de texto.",
    descriptionAr: "توليد موسيقى بالذكاء الاصطناعي ينشئ أغاني أصلية مع كلمات من تعليمات نصية.",
    category: "audio",
    tags: ["music", "song", "creative", "audio"],
    difficulty: "beginner",
    url: "https://suno.com",
    rating: r(4.5),
    pricing: "Free tier / from $10/mo",
    useCase: "Suno creates original songs with vocals and instruments from text descriptions. Great for content creators, musicians, and anyone exploring AI music.",
    icon: "\u{1F3B5}",
  },
  {
    id: "murf-ai",
    name: "Murf AI",
    description: "AI voiceover platform with natural-sounding voices for professional content creation.",
    descriptionEs: "Plataforma de locución IA con voces naturales para creación de contenido profesional.",
    descriptionAr: "منصة تعليق صوتي بالذكاء الاصطناعي بأصوات طبيعية لإنشاء المحتوى الاحترافي.",
    category: "audio",
    tags: ["voiceover", "tts", "professional", "narration"],
    difficulty: "beginner",
    url: "https://murf.ai",
    rating: r(4.3),
    pricing: "Free tier / from $19/mo",
    useCase: "Murf AI turns text into voiceovers for videos, e-learning, and presentations. It offers a wide range of natural voices with pitch and emphasis control.",
    icon: "\u{1F3A4}",
  },
  {
    id: "deeplearning-ai",
    name: "DeepLearning.AI",
    description: "World-class AI education platform offering courses from Andrew Ng and industry experts.",
    descriptionEs: "Plataforma de educación en IA de clase mundial con cursos de Andrew Ng y expertos de la industria.",
    descriptionAr: "منصة تعليم ذكاء اصطناعي عالمية المستوى تقدم دورات من Andrew Ng وخبراء الصناعة.",
    category: "learning",
    tags: ["courses", "education", "deep-learning", "certificate"],
    difficulty: "intermediate",
    url: "https://www.deeplearning.ai",
    rating: r(4.8),
    pricing: "Free / from $49/mo",
    useCase: "DeepLearning.AI offers structured AI courses from beginner to advanced. Andrew Ng's courses are the gold standard for learning machine learning and AI fundamentals.",
    icon: "\u{1F4DA}",
  },
  {
    id: "fast-ai",
    name: "fast.ai",
    description: "Practical deep learning education with a top-down teaching approach for developers.",
    descriptionEs: "Educación práctica en deep learning con un enfoque de enseñanza descendente para desarrolladores.",
    descriptionAr: "تعليم عملي للتعلم العميق بنهج تعليمي من الأعلى إلى الأسفل للمطورين.",
    category: "learning",
    tags: ["courses", "practical", "free", "deep-learning"],
    difficulty: "intermediate",
    url: "https://www.fast.ai",
    rating: r(4.6),
    pricing: "Free",
    useCase: "fast.ai teaches deep learning using a practical, code-first approach. Their free courses let you build production models quickly without heavy math prerequisites.",
    icon: "\u{1F3C3}",
  },
  {
    id: "langchain",
    name: "LangChain",
    description: "Framework for building LLM-powered applications with composable chains and agents.",
    descriptionEs: "Framework para construir aplicaciones impulsadas por LLM con cadenas y agentes componibles.",
    descriptionAr: "إطار عمل لبناء تطبيقات مدعومة بنماذج اللغة الكبيرة بسلاسل ووكلاء قابلين للتكوين.",
    category: "coding",
    tags: ["framework", "llm", "agents", "python"],
    difficulty: "advanced",
    url: "https://www.langchain.com",
    rating: r(4.5),
    pricing: "Free (open-source) / LangSmith paid",
    useCase: "LangChain builds applications on top of LLMs. Use it to create chatbots, RAG systems, AI agents, and automated workflows with chain composition.",
    icon: "\u{26D3}️",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    description: "Leading platform for open-source AI models, datasets, and collaborative ML development.",
    descriptionEs: "Plataforma líder para modelos de IA de código abierto, datasets y desarrollo colaborativo de ML.",
    descriptionAr: "المنصة الرائدة لنماذج الذكاء الاصطناعي مفتوحة المصدر ومجموعات البيانات وتطوير التعلم الآلي التعاوني.",
    category: "industry",
    tags: ["models", "open-source", "community", "mlops"],
    difficulty: "advanced",
    url: "https://huggingface.co",
    rating: r(4.7),
    pricing: "Free / paid inference and storage",
    useCase: "Hugging Face is the GitHub of AI. Access thousands of pre-trained models, datasets, and Spaces apps. Essential for ML engineers and AI researchers.",
    icon: "\u{1F917}",
  },
];
