"""
Fix compact format pricing tiers that are missing featuresZh.
The main script's tier handler consumes the line before the features handler runs.
"""
import re
from pathlib import Path

FILEPATH = Path(r"C:\Users\jun\aistudyonline-next\src\lib\tools.ts")

FEATURE_ZH = {
    "GPT-4o mini access": "GPT-4o mini访问权限",
    "Limited GPT-5 messages": "GPT-5消息有限额度",
    "Basic file uploads": "基础文件上传",
    "Unlimited GPT-5": "GPT-5无限使用",
    "Advanced data analysis": "高级数据分析",
    "DALL-E 3": "DALL-E 3图像生成",
    "Custom GPTs": "自定义GPTs",
    "Unlimited GPT-5 Turbo": "GPT-5 Turbo无限使用",
    "Priority access": "优先访问",
    "Extended context": "扩展上下文",
    "Claude 4 Sonnet": "Claude 4 Sonnet模型",
    "Limited daily messages": "每日消息限制",
    "Basic uploads": "基础文件上传",
    "Unlimited Claude 4 Sonnet": "Claude 4 Sonnet无限使用",
    "Claude 4 Opus": "Claude 4 Opus模型",
    "Projects": "项目管理",
    "All Pro features": "所有专业版功能",
    "Higher limits": "更高使用额度",
    "Shared workspaces": "共享工作区",
    "Gemini 2.0 Flash": "Gemini 2.0 Flash模型",
    "Google Search": "谷歌搜索",
    "File uploads": "文件上传",
    "Gemini 2.0 Pro": "Gemini 2.0 Pro模型",
    "1TB Drive storage": "1TB云盘存储",
    "Workspace integration": "工作区集成",
    "Unlimited DeepSeek chat": "DeepSeek无限聊天",
    "DeepSeek-R1": "DeepSeek-R1模型",
    "R1 and V3 API": "R1和V3 API",
    "Rate limits": "速率限制",
    "Fine-tuning": "模型微调",
    "Standard search": "标准搜索",
    "Limited Pro searches": "专业搜索有限额度",
    "Unlimited Pro": "专业搜索无限使用",
    "Unlimited file analysis": "文件分析无限使用",
    "API access": "API访问权限",
    "3.3 hrs/month GPU": "每月3.3小时GPU时长",
    "Commercial license": "商业使用授权",
    "15 hrs/month GPU": "每月15小时GPU时长",
    "Stealth mode": "隐身模式",
    "30 hrs/month GPU": "每月30小时GPU时长",
    "Priority queue": "优先队列",
    "Limited DALL-E 3": "DALL-E 3有限使用",
    "Basic resolution": "基础分辨率",
    "Unlimited DALL-E 3": "DALL-E 3无限使用",
    "HD resolution": "高清分辨率",
    "Unlimited generation": "无限生成",
    "Full privacy": "完全隐私保护",
    "All models": "所有模型",
    "Cloud hosted": "云端托管",
    "No GPU needed": "无需GPU",
    "25 credits/month": "每月25积分",
    "Basic features": "基础功能",
    "Express access": "Express访问权限",
    "100 credits/month": "每月100积分",
    "Full features": "全部功能",
    "Commercial use": "商业使用授权",
    "150 tokens/day": "每日150点数",
    "Standard models": "标准模型",
    "2500 tokens/month": "每月2500点数",
    "Faster generation": "更快的生成速度",
    "Limited generations": "有限生成次数",
    "720p export": "720p导出",
    "4K export": "4K导出",
    "Green screen": "绿幕功能",
    "All Pro": "所有专业版功能",
    "Collaboration": "团队协作",
    "Priority support": "优先支持",
    "Standard quality": "标准质量",
    "More generations": "更多生成次数",
    "HD quality": "高清质量",
    "Faster queue": "更快的处理队列",
    "1 min video": "1分钟视频",
    "Watermark": "包含水印",
    "Basic avatars": "基础虚拟形象",
    "10 mins/month": "每月10分钟",
    "No watermark": "无水印",
    "HD export": "高清导出",
    "30 mins/month": "每月30分钟",
    "Custom avatars": "自定义虚拟形象",
    "1 user": "1个用户",
    "50+ templates": "50多个模板",
    "SEO mode": "SEO模式",
    "3 users": "3个用户",
    "Brand voice": "品牌语气",
    "Custom templates": "自定义模板",
    "2000 words/month": "每月2000词",
    "Basic templates": "基础模板",
    "Unlimited words": "无限字数",
    "5 users": "5个用户",
    "Workflows": "工作流自动化",
    "Per member": "按成员计费",
    "AI writing": "AI写作",
    "Auto-fill databases": "自动填充数据库",
    "Basic grammar": "基础语法检查",
    "Spelling": "拼写检查",
    "Punctuation": "标点检查",
    "Full grammar": "完整语法检查",
    "Tone detection": "语气检测",
    "Plagiarism": "查重功能",
    "All Premium": "所有高级版功能",
    "Style guide": "风格指南",
    "Analytics": "数据分析",
    "200 AI completions": "200次AI补全",
    "Basic chat": "基础聊天",
    "Unlimited AI": "AI无限使用",
    "Agent mode": "代理模式",
    "Multi-file edit": "多文件编辑",
    "2000 completions/month": "每月2000次补全",
    "Code chat": "代码聊天",
    "Multi-file": "多文件支持",
    "PR summaries": "PR摘要生成",
    "Limited compute": "有限计算资源",
    "AI agent access": "AI代理访问",
    "Public projects": "公开项目",
    "Unlimited compute": "无限计算资源",
    "Private projects": "私有项目",
    "Faster AI": "更快的AI响应",
    "Limited AI credits": "有限AI额度",
    "All templates": "所有模板",
    "Export options": "导出选项",
    "Unlimited presentations": "无限演示文稿",
    "Brand control": "品牌控制",
    "Limited AI": "AI功能有限",
    "250K+ templates": "超过25万个模板",
    "1GB storage": "1GB存储空间",
    "100M+ assets": "超过1亿素材",
    "Brand kits": "品牌工具包",
    "10K chars/month": "每月1万字符",
    "Standard voices": "标准语音",
    "30K chars/month": "每月3万字符",
    "Voice cloning": "语音克隆",
    "100K chars/month": "每月10万字符",
    "5 songs/day": "每天5首",
    "Basic quality": "基础质量",
    "500 songs/month": "每月500首",
    "Full quality": "完整质量",
    "10 mins voice": "10分钟语音",
    "Limited voices": "有限语音选择",
    "24 hours/year": "每年24小时",
    "All voices": "所有语音",
    "Video access": "视频课程访问",
    "Limited exercises": "有限练习",
    "Full courses": "完整课程",
    "Certificate": "结业证书",
    "All course materials": "所有课程资料",
    "Forum access": "论坛访问权限",
    "Book included": "包含教材",
    "All framework features": "所有框架功能",
    "Self-hosted": "自行托管",
    "Debugging": "调试功能",
    "Monitoring": "监控功能",
    "Evaluation": "评估功能",
    "Public models": "公开模型",
    "Datasets": "数据集访问",
    "Limited Spaces": "有限Spaces额度",
    "Private repos": "私有仓库",
    "More Spaces": "更多Spaces额度",
    "Inference API": "推理API",
    "10,000 words/month": "每月1万字",
    "SEO optimization": "SEO优化",
    "5,000 chars/month": "每月5000字符",
    "40+ templates": "40多个模板",
    "50,000 chars/month": "每月5万字符",
    "Plagiarism check": "查重检查",
    "Custom tones": "自定义语气",
    "Limited paraphrasing": "有限改写次数",
    "Unlimited paraphrasing": "无限改写",
    "7 modes": "7种模式",
    "10 rephrases/day": "每天10次改写",
    "Basic modes": "基础模式",
    "Unlimited rephrases": "无限改写",
    "All modes": "所有模式",
    "Tone adjustment": "语气调整",
    "20,000 words/mo": "每月2万字",
    "Bulk generation": "批量生成",
    "Shopify sync": "Shopify同步",
    "5,000 AI words/mo": "每月5000AI词",
    "Basic scoring": "基础评分",
    "20,000 AI words/mo": "每月2万AI词",
    "Advanced scoring": "高级评分",
    "Integrations": "集成功能",
    "Higher quality": "更高质量",
    "Standard resolution": "标准分辨率",
    "Preview quality": "预览质量",
    "Batch processing": "批量处理",
    "Basic tools": "基础工具",
    "All tools": "所有工具",
    "Basic editing": "基础编辑",
    "Auto-captions": "自动字幕",
    "Templates": "模板",
    "Advanced effects": "高级特效",
    "Cloud storage": "云存储",
    "1 hour transcription": "1小时转录",
    "10 hours/mo": "每月10小时",
    "AI features": "AI功能",
    "Screen recording": "录屏功能",
    "10 mins video": "10分钟视频",
    "Standard avatars": "标准虚拟形象",
    "Dedicated support": "专属支持",
    "Watermarked": "含带水印",
    "Limited templates": "有限模板",
    "Stock media": "素材库",
    "Basic editors": "基础编辑器",
    "AI tools limited": "AI工具有限",
    "All AI tools": "所有AI工具",
    "Ad-free": "无广告",
    "Advanced features": "高级功能",
    "Web copilot": "网页版Copilot",
    "Limited daily chats": "每日聊天次数限制",
    "Full Office integration": "完整Office集成",
    "Copilot Studio": "Copilot Studio",
    "Enterprise security": "企业级安全",
    "300 mins/month": "每月300分钟",
    "Basic transcription": "基础转录",
    "1200 mins/month": "每月1200分钟",
    "Search": "搜索功能",
    "Limited transcription": "有限转录",
    "Public meetings": "公开会议",
    "Unlimited transcription": "无限转录",
    "Limited slides": "有限幻灯片数",
    "Basic themes": "基础主题",
    "Unlimited slides": "无限幻灯片",
    "Image generation": "图像生成",
    "Limited presentations": "有限演示文稿",
    "Basic AI": "基础AI功能",
    "Full AI": "全部AI功能",
    "Custom branding": "自定义品牌",
    "Managed indexing": "托管索引",
    "Local completions": "本地补全",
    "Limited suggestions": "有限建议",
    "Full completions": "完整补全",
    "Whole-line": "整行补全",
    "Team models": "团队模型",
    "Priority completions": "优先补全",
    "Limited requests": "有限请求",
    "Basic context": "基础上下文",
    "Unlimited requests": "无限请求",
    "Full context": "完整上下文",
    "Multiple repos": "多个仓库",
    "AI search limited": "AI搜索有限",
    "Team features": "团队功能",
    "Public docs": "公开文档",
    "Custom domain": "自定义域名",
    "Multiple users": "多用户支持",
    "Basic capture": "基础捕获",
    "Limited storage": "有限存储",
    "Unlimited storage": "无限存储",
    "Team sharing": "团队共享",
    "Advanced AI": "高级AI功能",
    "Limited searches": "有限搜索",
    "Basic models": "基础模型",
    "Unlimited searches": "无限搜索",
    "GPT-5/C4 Opus": "GPT-5/Claude Opus",
    "Priority": "优先处理",
    "60 articles": "60篇文章",
    "Basic analysis": "基础分析",
    "200 articles": "200篇文章",
    "AI generation": "AI生成",
    "30 articles/mo": "每月30篇文章",
    "Unlimited articles": "无限文章",
    "Full platform": "完整平台",
    "Custom analysis": "自定义分析",
    "Basic AI tools": "基础AI工具",
    "Limited content": "有限内容",
    "Full AI suite": "完整AI套件",
    "Content assistant": "内容助手",
    "Predictive scoring": "预测评分",
    "1,000 contacts": "1000个联系人",
    "AI flows": "AI流程",
    "Sequences": "序列功能",
    "10,000 contacts": "1万个联系人",
    "Local only": "仅本地运行",
    "CLI + API": "命令行和API",
    "GUI + API": "图形界面和API",
    "Local CPU": "本地CPU运行",
    "Offline": "离线运行",
    "Multi-provider": "多提供商支持",
    "Basic recording": "基础录制",
    "Audio cleanup": "音频清理",
    "Unlimited recording": "无限录制",
    "Revoice": "AI语音修复",
    "Publishing": "发布功能",
    "8000 tokens/month": "每月8000点数",
    "Export": "导出功能",
    "Team library": "团队资源库",
    "2 modes": "2种模式",
    "Basic summary": "基础摘要",
    "Export": "导出功能",
    "8000 tokens/month": "每月8000点数",
}

def q(s):
    return '"' + s + '"'

def main():
    with open(FILEPATH, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    changes = 0
    for i, line in enumerate(lines):
        stripped = line.strip()
        # Match compact format tier lines that have tier and features but NOT featuresZh
        if ('tier:' in stripped and 'features:' in stripped
            and 'featuresZh:' not in stripped
            and '{' in stripped and '}' in stripped):

            m = re.search(r'features:\s*\[([^\]]*)\]', stripped)
            if m:
                items = re.findall(r'"([^"]*)"', m.group(1))
                if items:
                    zh_items = [FEATURE_ZH.get(item, item) for item in items]
                    indent = len(line) - len(line.lstrip())

                    # Insert featuresZh before the closing }
                    before_brace = stripped.rstrip().rstrip(',').rstrip()
                    last_brace = before_brace.rfind('}')
                    if last_brace >= 0:
                        before = before_brace[:last_brace].rstrip()
                        after = before_brace[last_brace:]
                        zh_part = ', '.join(q(i) for i in zh_items)
                        new_line = ' ' * indent + before + ', featuresZh: [' + zh_part + '] ' + after.lstrip() + ',\n'
                        lines[i] = new_line
                        changes += 1
                        print(f"  Line {i+1}: added featuresZh ({', '.join(items)})")

    with open(FILEPATH, 'w', encoding='utf-8') as f:
        f.writelines(lines)

    print(f"\nTotal changes: {changes}")

if __name__ == '__main__':
    main()
