"""Publish Aug 6, 2026 — 1 article, no new tools."""
import os; BASE = r"C:\Users\jun\aistudyonline-next"; os.chdir(BASE)

with open('src/lib/articles.ts', 'r', encoding='utf-8') as f: s = f.read()
a = r"""  {
    slug: "build-your-first-personal-app-with-ai-even-without-coding-experience",
    title: "Build Your First Personal App with AI Even Without Coding Experience",
    titleZh: "零代码经验也能用AI搭建你的第一个个人应用",
    description: "A complete hands-on tutorial for building a personal work-and-life management app with AI — from prompt writing, PRD drafting, and Git archiving to secondary development and interface beautification. Zero programming experience required.",
    descriptionZh: "从零开始用AI搭建个人工作生活管理应用的完整教程——涵盖提示词编写、PRD文档、Git归档、二次开发和界面美化。无需编程经验。",
    category: "ai-tutorials",
    tags: ["AI App Development", "No Code", "Personal App", "AI Agent", "Prompt Engineering", "Git", "Beginner"],
    difficulty: "beginner",
    toolsMentioned: ["Doubao", "Trae", "Kimi", "Tongyi", "Cursor", "Claude", "Codex"],
    date: "2026-08-06",
  },

"""
last = s.rfind('];')
with open('src/lib/articles.ts', 'w', encoding='utf-8') as f: f.write(s[:last] + a + '];')
print('Part 1 done')

with open('src/lib/article-content.ts', 'r', encoding='utf-8') as f: c = f.read()
n = r'''
  "build-your-first-personal-app-with-ai-even-without-coding-experience": {
    content: `<div class="meta-banner">
  <span class="meta-badge">📖 AI Tutorials</span>
  <span class="meta-badge">🕒 10 min read</span>
  <span class="meta-badge">📅 Aug 6, 2026</span>
  <span class="meta-badge">🎯 Beginner</span>
</div>

<h2 id="introduction">Introduction</h2>
<p>This hands-on tutorial walks you through building a customized personal work-and-life management app from scratch, assuming zero programming and AI operation experience. The full workflow covers prompt writing, UI structure design, PRD drafting, development scheduling, first-version acceptance, Git version archiving, iterative secondary development, and interface beautification. The open-source project code of the finished app is also shared publicly, and you will learn to download the source code and add personalized features via AI secondary customization. By finishing this tutorial, you will own a dedicated app tailored for daily work and life management, plus the practical skill of software development assisted by AI tools.</p>

<h2 id="phase1">Phase 1: Prepare Local Project Folder and Select AI Agent</h2>

<h3>Step 1: Create a dedicated project folder</h3>
<p>Make a new blank folder on your local computer (desktop is used for demonstration; you may pick any familiar directory), and rename it <code>Muzi-APP</code>. All source code generated by AI for this app will be stored inside this folder for unified management.</p>

<h3>Step 2: Pick a suitable AI agent</h3>
<p>This tutorial works universally across mainstream intelligent agents and models including Doubao, Trae, Kimi, Tongyi, Cursor, Claude Code and Codex. If you already use one agent consistently, keep using it. If you are a beginner, choose a domestic AI agent to start the project. After launching the agent, you will enter the chat interface: the core working logic is submitting natural-language prompts to the AI to push project construction forward.</p>

<h3>Step 3: Import the project folder into the agent</h3>
<p>In the agent workspace, add the newly created <code>Muzi-APP</code> folder to grant the AI read and edit permissions for local project files.</p>

<h2 id="phase2">Phase 2: Write Structured Requirement Prompts and Clarify Demands</h2>

<h3>Standard prompt framework template</h3>
<p>Submit the first formal prompt with four core sections:</p>
<ol>
  <li><strong>One-sentence product positioning</strong> — e.g., "I want to build a personal-only work-and-life management app for my private use."</li>
  <li><strong>Functional module list</strong> — List independent modules with scenario-specific native features: homepage dashboard, daily schedule tracking, self-media operation management, development work record, client consulting archive, fitness plan, diet log, game entertainment record, data & system settings.</li>
  <li><strong>Data storage rule requirement</strong> — All user data must be saved as independent local files instead of browser cache; data shall remain intact after browser refresh, system reboot and cache clearance, and support manual backup and automatic scheduled backup.</li>
  <li><strong>Out-of-scope functions for V1</strong> — Do not implement account registration, multi-user permission system, cloud deployment and mobile terminal adaptation in the first version.</li>
</ol>
<p>Append an execution constraint at the end of the prompt:</p>
<pre><code class="language-plaintext">Do not start coding immediately. Confirm ambiguous details one question at a time via dialogue, restate the full sorted requirements only after full understanding, and wait for my confirmation before subsequent work.</code></pre>

<h3>Resolve ambiguous demands via AI follow-up questions</h3>
<p>The AI will raise targeted questions to confirm unclear details. For the storage-location question, select local independent file storage over browser cache to avoid accidental data loss caused by cache cleaning. After confirmation, the AI will return a full requirement recap that refines module details: the self-media module records topic inspiration, production schedule and publish date; the development module tracks pending tasks and bug logs; the consulting module archives client profiles and communication history. Revise unsatisfactory parts via continuous dialogue until the requirement recap matches your expectation.</p>

<h2 id="phase3">Phase 3: Design Page Structure and Interaction Logic</h2>
<p>Lock the finalized requirement scope first, then instruct the AI to output the full UI architecture without generating code at this stage. The classic layout features a left fixed navigation bar listing all functional modules, a central main content area for page details, and a right sidebar for entry editing and note recording. Review the page design draft module by module to confirm display rules for each page before moving forward.</p>

<h2 id="phase4">Phase 4: Generate Standard PRD</h2>
<p>Submit the prompt below to ask the AI to compile a formal PRD saved as <code>PRD.md</code>:</p>
<pre><code class="language-plaintext">Organize all confirmed requirements into a standard PRD document for development reference, covering these mandatory sections:
1. Product objective and usage scenarios
2. Overall page framework and navigation structure
3. Function description of each independent module
4. Data association logic across modules
5. Local file storage, backup and recovery specifications
6. Mandatory features for the first release
7. Features temporarily excluded from V1
8. Quantitative acceptance criteria for final delivery</code></pre>

<h3>Core value of the PRD file</h3>
<p>The PRD acts as a permanent construction blueprint: demand information will not get lost in long chat histories or when switching agents/models, and the AI can always refer to the PRD to keep development aligned with original expectations. The generated PRD defines the product positioning as a privatized local work-life management tool, clarifies storage persistence rules, lists priority features and excluded features, and sets measurable acceptance standards covering app startup access, data durability, module linkage and independent function performance.</p>

<h2 id="phase5">Phase 5: Make Executable Development Plan</h2>
<p>Send the prompt: <code>Generate a detailed actionable development plan based on PRD.md</code>. For users without technical backgrounds: the PRD is for you to verify demand rationality, while the development plan is the execution guideline for AI. A cost-saving optimization strategy is using high-performance models for drafting the development plan and switching to cost-effective models for subsequent coding. Add strict execution constraints in the development prompt:</p>
<pre><code class="language-plaintext">Develop strictly following the scheduled phases in order. Run targeted tests after finishing each phase; locate and fix bugs before advancing to the next phase. Complete all phases in sequence, never skip tests, delete test cases or lower acceptance standards to pass verification. Run full-round tests after the whole project is finished.</code></pre>

<h2 id="phase6">Phase 6: First-Version Development and Acceptance Test</h2>
<p>The AI will complete all nine development phases automatically, deliver startup scripts (<code>启动木子工作台.command</code> for macOS and the Windows counterpart) or a direct web access URL. Double-click the startup script or open the URL to launch the V1 app for full acceptance inspection.</p>

<h3>Key problems found in the demo acceptance</h3>
<ol>
  <li>The original interface lacks visual design and aesthetic effects</li>
  <li>The self-media module has no data visualization charts for post-performance metrics like views, likes and collections</li>
  <li>The development work module lacks entry buttons for adding new work items</li>
  <li>The consulting module only supports adding clients without the deletion function</li>
  <li>Fitness and diet modules need calendar-style display for daily training records and meal logs</li>
  <li>No manual data backup button is available</li>
</ol>
<p>Record all defects clearly for the secondary development phase.</p>

<h2 id="phase7">Phase 7: Git Archive for Version Management</h2>
<p>Allocate a recoverable checkpoint for the finished V1 version before optimization:</p>
<ol>
  <li>Run the prompt to let the AI detect Git installation status and complete installation automatically if missing:
    <pre><code class="language-plaintext">Check whether Git has been installed on the current device; install Git officially and safely matching the operating system if it is unavailable.</code></pre>
  </li>
  <li>Initialize the local Git repository: <code>Initialize a local Git repository in the current project directory</code></li>
  <li>Submit the first official version: <code>feat: finish V1 Muzi workstation release</code></li>
</ol>
<p>Git version archiving prevents irreversible damage to stable functions caused by subsequent iterative adjustments; you can roll back to the stable V1 version anytime if optimization fails.</p>

<h2 id="phase8">Phase 8: Secondary Development for Bug Fixes and Feature Iteration</h2>
<p>Submit one problem to the AI per round, trigger Git commit after each bug is fixed and tested successfully, and iterate the six recorded defects one by one:</p>
<ul>
  <li>Add performance data dashboard in the self-media module</li>
  <li>Create dedicated entry buttons for adding work items in the development module</li>
  <li>Enable client deletion permission in the consulting module</li>
  <li>Switch fitness and diet modules to calendar layout</li>
  <li>Add independent manual backup button in the data settings page</li>
</ul>
<p>Verify each repaired function in the live app after iteration.</p>

<h2 id="phase9">Phase 9: Multi-Style Interface Beautification</h2>
<p>The beautification operation only adjusts visual presentation without altering existing core functions. You can reference the design language of mature third-party apps and submit corresponding prompts to replicate styles:</p>
<ul>
  <li><strong>macOS frosted glass style</strong>: adopt Liquid Glass design language with translucent card components and soft gradient background</li>
  <li><strong>Notion note style</strong>: clean minimalist layout with optional light/dark theme switching</li>
  <li><strong>Neo-Brutalism style</strong>: high-contrast color blocks, prominent interactive animation and independent light/dark modes</li>
</ul>
<p>All original functional modules remain fully usable after skin switching.</p>

<h2 id="phase10">Phase 10: Acquire Open-Source Code for Independent Secondary Development</h2>
<p>The finished project is open-sourced on GitHub, and beginners can obtain the source code with zero programming foundation following these steps:</p>
<ol>
  <li>Enter the repository page <code>TianyidataScience / my-own-app</code> on GitHub</li>
  <li>Click <code>Code</code> → <code>Download ZIP</code> to export the compressed source-code package</li>
  <li>Unzip the package, import the folder into your AI agent workspace</li>
  <li>Send the prompt to install runtime dependencies automatically:
    <pre><code class="language-plaintext">Install all required project dependencies and run a minimal startup validation, reserve complete original code and unmodified data structure after deployment.</code></pre>
  </li>
  <li>Run the corresponding startup script for your operating system: <code>.command</code> for macOS and <code>.bat</code> for Windows</li>
</ol>

<h3>Example of adding new custom modules</h3>
<p>To build a reading management module, submit the prompt below to the AI for automatic development:</p>
<pre><code class="language-plaintext">Add an independent reading module supporting book entry management, reading progress statistics and reading note editing; integrate the module with the existing data framework of the original project.</code></pre>
<p>The AI will generate statistical dashboards, note entry forms and progress charts for the new reading module automatically.</p>

<h2 id="conclusion">Final Takeaway</h2>
<p>Whether you follow the full tutorial step by step or adjust modules based on your personal demands, you can build a fully customized exclusive app with AI assistance. Making AI a regular programming partner can greatly improve personal development efficiency even for users with zero coding background. Open-source repository: <a href="https://github.com/TianyidataScience/my-own-app" target="_blank" rel="noopener noreferrer">TianyidataScience / my-own-app</a>.</p>

<h2>常见问题</h2>

<h3>Do I really need zero coding experience to follow this tutorial?</h3>
<p>Yes. The entire workflow is designed for complete beginners. You never write a single line of code manually — all coding is done by the AI agent through natural language prompts. The only skills you need are: (1) creating a folder on your computer, (2) typing text into a chat interface, and (3) double-clicking a file to run it. If you can use a web browser and a text editor, you can follow every step of this tutorial. The PRD phase and Git phase are also handled by the AI through prompts — you just review and confirm the outputs.</p>

<h3>Which AI agent should I choose as a beginner?</h3>
<p>For Chinese-speaking beginners, domestic agents like Doubao or Tongyi are recommended because they handle Chinese prompts most naturally, have no network restrictions, and offer free tiers sufficient for completing this tutorial. For English-speaking users, Claude Code or Cursor provide more advanced coding capabilities. The tutorial works identically across all agents — the difference is only in the chat interface and model behavior. The key is to pick one and stick with it throughout the entire workflow rather than switching agents mid-project, which can cause context loss.</p>

<h3>What kind of app can I actually build with this method?</h3>
<p>The tutorial builds a personal work-and-life management app with these modules: homepage dashboard (showing today's overview), daily schedule tracker, self-media content management (topic inspiration, production schedule, publish tracking), development task tracker (pending tasks, bug logs), client consulting archive (profiles, communication history), fitness plan manager, diet log, game entertainment tracker, and data/system settings. The app runs entirely locally in your browser — no cloud deployment, no account system, no mobile adaptation. All data is stored as local files, so it survives browser cache clears and system reboots. Once you finish the tutorial, you can customize the modules to fit your own needs (e.g., replace the fitness module with a reading tracker).</p>

<h3>Why is Git version control important for an AI-built app?</h3>
<p>Git version control is the safety net that makes AI-assisted development practical. When you ask the AI to add new features or fix bugs, there is always a risk that the changes break existing functionality. Git lets you: (1) save a stable checkpoint (V1) before any modifications, (2) commit after each successful bug fix so you can roll back individual changes, and (3) compare versions to see exactly what the AI changed. Without Git, a single failed AI modification could corrupt your entire app with no way to recover. The tutorial handles all Git commands through AI prompts — you never need to type a git command manually.</p>

<div class="next-step">
  <h3>📖 Next Steps</h3>
  <p>Mastered the basics of AI-assisted app development? Level up your skills:</p>
  <ul>
    <li><a href="/articles/master-ai-driven-development-with-openspec-practical-guide-beginners">Master AI-Driven Development with OpenSpec: A Practical Guide for Beginners</a> — take AI app development to the next level with structured spec-driven workflows</li>
    <li><a href="/articles/vibecoding-contest-guide-create-game-animations-efficiently-with-ai-tools">VibeCoding Contest Guide: Create Game Animations Efficiently With AI Tools</a> — learn to build game animations with AI, a natural next step after building your first app</li>
    <li><a href="/articles/claude-code-zero-to-hero-practical-guide">Claude Code Zero-to-Hero: A 9-Minute Practical Guide for Beginners</a> — dive deeper into the most powerful AI coding assistant for serious projects</li>
  </ul>
</div>`,
    contentZh: `<div class="meta-banner">
  <span class="meta-badge">📖 AI教程</span>
  <span class="meta-badge">🕒 阅读约10分钟</span>
  <span class="meta-badge">📅 2026年8月6日</span>
  <span class="meta-badge">🎯 入门</span>
</div>

<h2 id="introduction">引言</h2>
<p>本教程手把手教你从零搭建一个专属的个人工作生活管理应用，假设你没有任何编程和AI操作经验。完整流程涵盖提示词编写、UI结构设计、PRD文档撰写、开发排期、首版验收、Git版本归档、迭代二次开发和界面美化。成品应用的开源代码也公开共享，你将学会下载源码并通过AI二次定制增加个性化功能。完成本教程后，你将拥有一个专为日常工作和生活管理定制的应用，以及AI辅助软件开发的实际技能。</p>

<h2 id="phase1">第一阶段：准备本地项目文件夹和选择AI助手</h2>

<h3>步骤1：创建专用项目文件夹</h3>
<p>在本地电脑上新建一个空白文件夹（视频中演示使用桌面，你可以选择任何熟悉的目录），重命名为<code>Muzi-APP</code>。AI为此应用生成的所有源代码都将存储在此文件夹中统一管理。</p>

<h3>步骤2：选择合适的AI助手</h3>
<p>本教程兼容豆包、Trae、Kimi、通义千问、Cursor、Claude Code和Codex等主流AI助手和模型。如果你已经有固定使用的AI助手，继续使用即可。如果你是初学者，建议选择国内AI助手开始项目。启动AI助手后，进入对话界面：核心工作逻辑是向AI提交自然语言提示词来推动项目构建。</p>

<h3>步骤3：将项目文件夹导入AI助手</h3>
<p>在AI助手工作区中，添加新创建的<code>Muzi-APP</code>文件夹，授予AI读取和编辑本地项目文件的权限。</p>

<h2 id="phase2">第二阶段：编写结构化需求提示词并通过对话明确需求</h2>

<h3>标准提示词框架模板</h3>
<p>提交第一个正式提示词，包含四个核心部分：</p>
<ol>
  <li><strong>一句话产品定位</strong> — 例如："我想搭建一个仅供个人使用的工作生活管理应用"</li>
  <li><strong>功能模块列表</strong> — 列出独立模块：首页仪表盘、日程追踪、自媒体运营管理、开发工作记录、客户咨询归档、健身计划安排、饮食日志、游戏娱乐记录、数据和系统设置</li>
  <li><strong>数据存储规则要求</strong> — 所有用户数据必须保存为独立本地文件而非浏览器缓存；刷新页面、重启系统和清除缓存后数据保持不变，支持手动备份和自动定时备份</li>
  <li><strong>V1版本不实现的功能</strong> — 首次版本不做账号注册、多用户权限系统、云部署和移动端适配</li>
</ol>
<p>在提示词末尾附加执行约束：</p>
<pre><code class="language-plaintext">不要立即开始编码。通过对话逐一确认模糊细节，完全理解后重新整理完整需求，等待我确认后再进行后续工作。</code></pre>

<h3>通过AI追问解决模糊需求</h3>
<p>AI会提出针对性问题来确认不清楚的细节。对于存储位置问题，选择本地独立文件存储而非浏览器缓存，避免因清理缓存导致数据丢失。确认后，AI会返回完整的需求总结，细化模块细节：自媒体模块记录选题灵感、制作进度和发布日期；开发模块跟踪待办任务和Bug日志；咨询模块归档客户档案和沟通记录。通过持续对话修改不满意部分，直到需求总结符合你的期望。</p>

<h2 id="phase3">第三阶段：设计页面结构和交互逻辑</h2>
<p>先锁定最终确定的需求范围，然后指示AI输出完整的UI架构，此阶段不生成代码。经典布局采用左侧固定导航栏列出所有功能模块、中央主内容区显示页面详情、右侧边栏用于条目编辑和笔记记录。逐模块审查页面设计稿，确认每个页面的显示规则后再推进。</p>

<h2 id="phase4">第四阶段：生成标准PRD文档</h2>
<p>提交以下提示词，让AI编译一份正式的PRD文档保存为<code>PRD.md</code>：</p>
<pre><code class="language-plaintext">将所有已确认的需求整理成标准PRD文档供开发参考，包括以下必需部分：
1. 产品目标和使用场景
2. 整体页面框架和导航结构
3. 每个独立模块的功能说明
4. 模块间的数据关联逻辑
5. 本地文件存储、备份和恢复规范
6. 首次发布必须实现的功能
7. V1版本暂不实现的功能
8. 最终交付的量化验收标准</code></pre>

<h3>PRD文件的核心价值</h3>
<p>PRD充当永久性的构建蓝图：需求信息不会在长对话历史中丢失，也不会在切换AI助手或模型时丢失，AI可以随时参考PRD确保开发符合原始预期。生成的PRD将产品定位为私有化本地工作生活管理工具，明确存储持久化规则，列出优先功能和排除功能，并设定可衡量的验收标准，涵盖应用启动访问、数据持久性、模块联动和独立功能性能。</p>

<h2 id="phase5">第五阶段：制定可执行的开发计划</h2>
<p>发送提示词：<code>根据PRD.md生成详细可操作的开发计划</code>。对于非技术背景的用户：PRD是让你验证需求合理性，而开发计划是AI的执行指南。一个节省成本的优化策略是使用高性能模型起草开发计划，切换到经济型模型进行后续编码。在开发提示词中添加严格的执行约束：</p>
<pre><code class="language-plaintext">严格按照排定的阶段顺序开发。完成每个阶段后运行针对性测试；定位并修复Bug后再进入下一阶段。按顺序完成所有阶段，绝不跳过测试、删除测试用例或降低验收标准来通过验证。整个项目完成后运行全量测试。</code></pre>

<h2 id="phase6">第六阶段：首版开发和验收测试</h2>
<p>AI会自动完成所有9个开发阶段，交付启动脚本（macOS的<code>启动木子工作台.command</code>和Windows对应版本）或直接提供网页访问URL。双击启动脚本或打开URL即可启动V1应用进行完整验收检查。</p>

<h3>演示验收中发现的关键问题</h3>
<ol>
  <li>原始界面缺乏视觉设计和美学效果</li>
  <li>自媒体模块缺少数据可视化图表来展示浏览量、点赞和收藏等作品表现指标</li>
  <li>开发工作模块缺少添加新工作项的入口按钮</li>
  <li>咨询模块只支持添加客户，缺少删除功能</li>
  <li>健身和饮食模块需要日历样式显示每日训练记录和饮食日志</li>
  <li>没有手动数据备份按钮</li>
</ol>
<p>清晰记录所有缺陷，供二次开发阶段使用。</p>

<h2 id="phase7">第七阶段：Git归档版本管理</h2>
<p>在优化前为已完成的V1版本分配可恢复的检查点：</p>
<ol>
  <li>运行提示词让AI检测Git安装状态，如缺失则自动安装：
    <pre><code class="language-plaintext">检查当前设备是否已安装Git；如果未安装，请安全地安装与操作系统匹配的官方Git版本。</code></pre>
  </li>
  <li>在项目文件夹中初始化本地Git仓库：<code>在当前项目目录中初始化本地Git仓库</code></li>
  <li>提交第一个正式版本：<code>feat: finish V1 Muzi workstation release</code></li>
</ol>
<p>Git版本归档可防止后续迭代调整对稳定功能造成不可逆的破坏；如果优化失败，可随时回滚到稳定的V1版本。</p>

<h2 id="phase8">第八阶段：二次开发修复Bug和功能迭代</h2>
<p>每轮向AI提交一个问题，修复并测试成功后触发Git提交，逐一解决记录的六个缺陷：</p>
<ul>
  <li>在自媒体模块中添加效果数据仪表盘</li>
  <li>在开发模块中创建添加工作项的专用入口按钮</li>
  <li>在咨询模块中启用客户删除权限</li>
  <li>将健身和饮食模块切换为日历布局</li>
  <li>在数据设置页面中添加独立的手动备份按钮</li>
</ul>
<p>每次迭代后在真实应用中验证修复的功能。</p>

<h2 id="phase9">第九阶段：多风格界面美化</h2>
<p>美化操作只调整视觉呈现，不改变现有核心功能。你可以参考成熟第三方应用的设计语言，提交相应提示词来复制风格：</p>
<ul>
  <li><strong>macOS毛玻璃风格</strong>：采用Liquid Glass设计语言，半透明卡片组件和柔和渐变背景</li>
  <li><strong>Notion笔记风格</strong>：简洁极简布局，支持浅色/深色主题切换</li>
  <li><strong>新粗野主义风格</strong>：高对比色块、突出的交互动画和独立的浅色/深色模式</li>
</ul>
<p>切换皮肤后所有原始功能模块仍然完全可用。</p>

<h2 id="phase10">第十阶段：获取开源代码进行独立二次开发</h2>
<p>成品项目在GitHub上开源，零编程基础的初学者可按以下步骤获取源代码：</p>
<ol>
  <li>进入GitHub仓库页面 <code>TianyidataScience / my-own-app</code></li>
  <li>点击 <code>Code</code> → <code>Download ZIP</code> 导出压缩源码包</li>
  <li>解压后导入文件夹到AI助手工作区</li>
  <li>发送提示词自动安装运行时依赖：
    <pre><code class="language-plaintext">安装所有必需的项目依赖并运行最小启动验证，部署后保留完整原始代码和未修改的数据结构。</code></pre>
  </li>
  <li>运行对应操作系统的启动脚本：macOS使用<code>.command</code>，Windows使用<code>.bat</code></li>
</ol>

<h3>添加新自定义模块示例</h3>
<p>要构建阅读管理模块，向AI提交以下提示词即可自动开发：</p>
<pre><code class="language-plaintext">添加一个独立的阅读模块，支持书籍录入管理、阅读进度统计和阅读笔记编辑；将该模块与原始项目现有的数据框架集成。</code></pre>
<p>AI会自动为新阅读模块生成统计仪表盘、笔记录入表单和进度图表。</p>

<h2 id="conclusion">总结</h2>
<p>无论你是按完整教程逐步操作，还是根据个人需求调整模块，你都可以借助AI构建一个完全定制的专属应用。即使零编程背景，让AI成为常规编程伙伴也能极大提升个人开发效率。开源仓库：<a href="https://github.com/TianyidataScience/my-own-app" target="_blank" rel="noopener noreferrer">TianyidataScience / my-own-app</a>。</p>

<h2>常见问题</h2>

<h3>真的需要零编程经验才能学习本教程吗？</h3>
<p>是的。整个工作流专为完全初学者设计。你不需要手动编写任何代码——所有编码工作都由AI通过自然语言提示词完成。你只需要三个技能：(1)在电脑上创建文件夹，(2)在对话界面中输入文字，(3)双击文件运行。如果你会使用网页浏览器和文本编辑器，就可以按照本教程的每一步操作。PRD阶段和Git阶段也由AI通过提示词处理——你只需审查和确认输出结果。</p>

<h3>作为初学者应该选择哪个AI助手？</h3>
<p>对于中文用户，推荐豆包或通义千问等国内AI助手，因为它们处理中文提示词最自然、无网络限制，且提供足够完成本教程的免费额度。对于英文用户，Claude Code或Cursor提供更先进的编码能力。本教程在所有AI助手上运行效果一致——区别仅在于对话界面和模型行为。关键是选择一个并坚持在整个工作流中使用，而不是中途切换AI助手，以免导致上下文丢失。</p>

<h3>使用这种方法能构建什么样的应用？</h3>
<p>本教程构建一个个人工作生活管理应用，包含以下模块：首页仪表盘（显示今日概览）、日程追踪器、自媒体内容管理（选题灵感、制作进度、发布追踪）、开发任务追踪（待办任务、Bug日志）、客户咨询归档（档案、沟通记录）、健身计划管理、饮食日志、游戏娱乐记录以及数据和系统设置。该应用完全在本地浏览器中运行——无需云部署、无需账号系统、无需移动端适配。所有数据存储为本地文件，因此清除浏览器缓存和系统重启后数据仍然保留。</p>

<h3>为什么Git版本控制对AI构建的应用如此重要？</h3>
<p>Git版本控制是让AI辅助开发变得实用的安全网。当你要求AI添加新功能或修复Bug时，总存在修改破坏现有功能的风险。Git让你可以：(1)在修改前保存稳定的检查点（V1版本），(2)每次成功修复Bug后提交，以便逐个回滚更改，(3)比较版本以查看AI具体更改了什么。没有Git，一次失败的AI修改可能破坏整个应用且无法恢复。本教程通过AI提示词处理所有Git命令——你无需手动输入任何Git命令。</p>

<div class="next-step">
  <h3>📖 下一步</h3>
  <p>掌握了AI辅助应用开发的基础？提升你的技能：</p>
  <ul>
    <li><a href="/articles/master-ai-driven-development-with-openspec-practical-guide-beginners">掌握OpenSpec驱动开发：初学者实用指南</a> — 通过结构化规范驱动的工作流将AI应用开发提升到新水平</li>
    <li><a href="/articles/vibecoding-contest-guide-create-game-animations-efficiently-with-ai-tools">VibeCoding比赛指南：用AI工具高效创作游戏动画</a> — 学习用AI构建游戏动画，这是构建第一个应用后的自然下一步</li>
    <li><a href="/articles/claude-code-zero-to-hero-practical-guide">Claude Code从零到精通：9分钟初学者实用指南</a> — 深入了解最强大的AI编码助手，为严肃项目做准备</li>
  </ul>
</div>`,
  },

'''
last = c.rfind('};')
with open('src/lib/article-content.ts', 'w', encoding='utf-8') as f: f.write(c[:last] + n + '};')
print('Part 2 done\n=== Done ===')